    IMPLICIT DOUBLE PRECISION (A-H,O-Z)

    REAL :: Kb,La,TEM,Lp,PHI,tbr,trep,RATIO,Le,DL1,DT,PI,MARK,CONST,G0,BR
	REAL :: G2,REMAIN,D0,RND,FL(4),RELAX,Dnd,CLIST(20050,600),G1,A(60,40)
	REAL :: DL2(4),FIC,ZETA,Vs,RLnd,d,W,DW,TL,tp,te,INDEX2,SCALE
	REAL :: CLF(20050,8),GGF(5000),GGGF(5000),GGR,GGGR,GGL,GGGL,FIC2,ALPHA
	REAL :: ST,OS,DLENGTH(5050,6),LAV(20050,6),LBAR,G(5000),T(5000),OPT1,PC
	REAL :: GF(5000),TAO(60,40),ERR(60),TAGET_A(40),SUM,TAGET_TAO(40),MINI
	REAL :: TAGET_B(40),XCH1(40),PM,B(60,40),INDEX1,F_ERR,OPT2,tMAX
    REAL :: C1,C2,FQ(5000),GG(5000),GGG(5000),FQMA,FQMI,GGMA,TERM
	REAL :: GGGMA,GGGMI,PLR,PUR,FQFMA,GGFMA,GGGFMA,FQFMI,GGFMI,GGGFMI,GGMI
	REAL :: FMI,FMA,LpMI,LpMA,APHMA,APHMI,FERR1,FERR2,FERR3,GGE(5000),tMIN
	REAL :: GGGE(5000),RATIOMI,RATIOMA,dMA,dMI,FERR4,ECPC1,trep1,Zf1
	REAL :: ECPC2,G0MA,trepMA,Zf,INDEX,G0ER1,G01,LpL
	REAL :: d1,d2,FERR,Lp0,dER1,dER2,RATIO1,ALPHA1,trep2,G0MI,PERR,FERRMA
	REAL ::	ALPHAF,LpF,dF,G0F,RATIOF,trepF,ZfF,FERRM,PERR1,PERR2,PERR3,LpU
	REAL :: PERRM,G0ER2,RATIOU,RATIOL,trepU,trepL,ZfU,ZfL,PERR4,RATIOUU,PLp
	REAL :: LpUU,LpLL,RATIOLL,trepUU,trepLL,FERR5,FLAGGE,DISP,PURMA,PURMI
	REAL :: PLRMA,PLRMI,Cb,Pb,CC1,P1,CC2,OPTK1,OPTK2,PCOR,CCOR,trepMI,FQC
	REAL :: FQFC,PERRMA,FQSC,FQFSC,PERR5

    INTEGER :: N,I,J,K,JJ,KK,TT,III,LPI1(4),LBR,LREC1,LREC2,LSI,NEWL1,JJJ
	INTEGER :: LSEG,LENGTH(5050,6),KKK,NEWL2,LMAP(20050,6),NUM,REM,Z,FLAGW
	INTEGER :: ICOUNT,KKKK,NNN,ITER,FLAG,BREATH,NUMOU,NLF,NLFL,LDR,FLAGJJ
    INTEGER :: ISIZE,IDATE(8),NLFU,SAMPLE,POINT,NN,JJJJ,NUMG,DR,SUM1,SUM2
	INTEGER :: GENERATION,II,XCH,CHECK,RESCALE,LROUSE,LBREATH,LBEND,FLAGR
	INTEGER :: NUMIN,FLAGF,FLAGMI,IDMA,IDMI,NM,IDH,FLAGH,M,SERRM2,SERRM1
	INTEGER :: JJF,FLAGG,FLAGPR,FLAGMR,GEP(5,40),GEN(5,10),KINK1,KINK2
	INTEGER :: FLAGMM,SLP,SD,OUTGT,OUTL,OUTGW,OUTGFT,OUTR
    INTEGER,ALLOCATABLE :: ISEED(:)

	CHARACTER :: TITLE,ANS1,ANS2,ANS3
																										

!==================================================================
!				         INPUT PARAMETER
!==================================================================

 	Kb=1.381E-23                 ! BOLTZMANN CONSTANT
	PI=3.141592653   			 ! CONSTANT PI
	Vs=0.000891        		     ! SOLVENT VISCOSITY
    PHI=0.0662                   ! VOLUME FRACTION	
	TEM=298.15				     ! SYSTEMIC TEMPERATURE

    CALL DATE_AND_TIME(VALUES=IDATE)
    CALL RANDOM_SEED(SIZE=ISIZE)
    ALLOCATE(ISEED(ISIZE))
    ISEED=ISEED*(IDATE(6)+IDATE(5)+IDATE(7))
    CALL RANDOM_SEED(PUT=ISEED)

	FMA=5.						 ! THE ORDER OF MAXIMUM FREQUENCY OF EXPERIMENTAL DATA 
	FMI=-2.						 ! THE ORDER OF MINIMUM FREQUENCY OF EXPERIMENTAL DATA
	APHMA=8.					 ! THE UPPPER BOUNDARY OF Le/Lp
	APHMI=0.1					 ! THE LOWER BOUNDARY OF Le/Lp
	RATIOMA=50.			    	 ! THE UPPPER BOUNDARY OF BREAKAGE RATE (ZETA)
	RATIOMI=1.*10.**(-3.)        ! THE LOWER BOUNDARY OF BREAKAGE RATE (ZETA)
	LpMA=2.5*10**(-7.)			 ! THE UPPPER BOUNDARY OF Lp
	LpMI=1.5*10**(-8.)			 ! THE LOWER BOUNDARY OF Lp
	trepMA=100.    		    	 ! THE UPPER BOUNDARY OF trep
	trepMI=0.002				 ! THE LOWER BOUNDARY OF trep
	dMI=2.*10**(-9.)		     ! THE UPPPER BOUNDARY OF MICELLE DIAMETER d
	dMA=8.*10**(-9.)			 ! THE LOWER BOUNDARY OF MICELLE DIAMETER d
	DTL=10**(-6.)			     ! TIME STEP CONSTANT
	NNN=13						 ! ITERATIONS FOR PARAMETER FITTING 

	LBREATH=1					 ! THE SWITCHER FOR CLF
	LDR=1						 ! THE SWITCHER FOR DOUBLE REPTATION
	LROUSE=1					 ! THE SWITCHER FOR ROUSE MODES
	LBEND=1						 ! THE SWITCHER FOR BENDING	MODES
	SD=1						 ! THE SWITCHER FOR MODIFTING d DURING ITERATIONS
	SLP=1						 ! THE SWITCHER FOR MODIFTING lp DURING ITERATIONS

	PC=0.5				         ! PROBABILITY OF PERMUTATION
	PM=0.05 	 		         ! PROBABILITY OF MUTATION
	GENERATION=15000 	         ! GENERATION NUMBER
	PURMA=3.					 ! THE MAXIMUM ORDER OF UPPER BOUNDARY FOR TAO_I IN GA 
	PURMI=-0.5					 ! THE MINIMUM ORDER OF UPPER BOUNDARY FOR TAO_I IN GA
	PLRMA=-3.5					 ! THE MAXIMUM ORDER OF LOWER BOUNDARY FOR TAO_I IN GA
	PLRMI=-8.					 ! THE MINIMUM ORDER OF LOWER BOUNDARY FOR TAO_I IN GA
	NLFU=200			         ! MAXIMUM INCREASE OF MICELLE NUMBER
	NLFL=-200			         ! MAXIMUM DECREASE OF MICELLE NUMBER
	NN=20					   	 ! APPROXIMATE PARAMETER NUMBER

	ECPC1=0.5					 ! RELAXATION FACTOR OF EMPIRICAL FORMULA BASED FITTING
	ECPC2=1.					 ! RELAXATION FACTOR OF ERROR BASED FITTING
	PCOR=1.	
	CCOR=1.
	Cb=1.33						 ! PREFACTOR FOR CRITICAL VALUE OF Z SEPARATE TWO REGIMES
	Pb=-1.25					 ! POWER FOR CRITICAL VALUE OF ENTANGLEMENT NUMBER BETWEEN TWO REGIMES 
	CC1=1.05					 ! PREFACTOR OF EMPIRICAL FORMULA (Z V.S. G"MIN) WHEN A=1
	P1=-0.24					 ! POWER OF ZETA FOR EMPIRICAL FORMULA (Z V.S. G"MIN) WHEN A=1
		 
	JJJ=0						 ! TESTING NUMBER
	NUM=5000					 ! ENSEMBLE SIZE
	NUMOU=200					 ! NUMBER OF OUTPUT DATA 
	DW=(FMA-FMI)/NUMOU			 ! INTERVAL OF FREQUENCY	  

	FLAGMR=0					 ! FLAG FOR PURE MECHANICAL DATA
	FLAGF=1						 ! FLAG FOR INCLUDING FREQUECNY INFORMATION
	FLAGR=0						 ! FLAG FOR FINDING THE MAXIMUM G" IN EXPERIMENTAL DATA
	FLAGMI=0					 ! FLAG FOR FINDING THE MINIMUM G" IN EXPERIMENTAL DATA
	FLAGH=0						 ! FLAG FOR HIGH FREQUECNY EXPERIMENTAL DATA AVAILABLE
	FLAGMM=0					 ! FLAG FOR NO APPEARANT MAXIMUM AND MINIMUM G" IN EXPERIMENTAL DATA
	FLAGJJ=0					 ! FLAG FOR ENDING THE ITERATIONS AUTOMATICALLY
	FLAGG=0						 ! FLAG FOR FIXING TAO_I FOR GA

    OPEN(20,FILE='OUTPUT_v1.6.2.DAT')	 ! PARAMETER AND FITTING ERROR EVOLUTION OUTPUT FILE
	OPEN(23,FILE='TIME_FREQUENCY TRANSFORMATION.DAT')	! MIU_I&TAO_I OUTPUT FILE 
	OPEN(24,FILE='SIMULATION MONITOR.DAT')  ! PROCESSION OF SIMULATION OUTPUT FILE

!==================================================================
!				         READING INPUT FILE
!==================================================================

											 
	OPEN(16,FILE='SAMPLE_INPUT_v1.6.2.DAT')	! EXPERIMENTAL DATA INPUT FILE
	READ(16,*) TITLE
	READ(16,*) TEM,PHI,Vs

	READ (16,*) ANS1
	IF (ANS1.EQ.'Y') THEN
	FLAGF=1
	END IF

	READ(16,*) ANS1
	IF (ANS1.EQ.'Y') THEN
	FLAGMR=1
	END IF

	READ(16,*) ANS1,ANS2,ANS3
	IF (ANS1.EQ.'Y') THEN
	OUTGT=1
	END IF
 	IF (ANS2.EQ.'Y') THEN
	OUTGFT=1
	END IF
	IF (ANS3.EQ.'Y') THEN
	OUTL=1
	END IF

	READ(16,*) ANS1,ANS2
	IF (ANS1.EQ.'Y') THEN
	OUTGW=1
	END IF
 	IF (ANS2.EQ.'Y') THEN
	OUTR=1
	END IF

	READ(16,*) ANS1,ANS2
	IF (ANS1.EQ.'Y') THEN
	SLP=0
	END IF
	IF (ANS2.EQ.'Y') THEN
	SD=0
	END IF 
	READ(16,*) RATIO,Lp,d
	READ(16,*) NUM
	READ(16,*) NNN
	Lp=Lp*10**(-9.)		         ! PERSISTENT LENGTH 
	d=d*10**(-9.)			     ! MICELLE DIAMETER

	NUMIN=0
	IF (FLAGF.EQ.1) THEN
    DO I=1,1000
	READ (16,*,END=11) FQ(I),GG(I),GGG(I)
	NUMIN=NUMIN+1
    END DO 
	ELSE
    DO I=1,1000
	READ (16,*,END=10) GG(I),GGG(I)
	NUMIN=NUMIN+1
    END DO
	END IF
10	DO I=1,NUMIN
    FQ(I)=10**(FMI+DW*I)
	END DO

11	CLOSE(16)
	WRITE(24,*) 'READ DATA FINISH'
	WRITE(*,*) 'READ DATA FINISH'

	TERM=LOG10(0.2/FQ(1))

	IF (FLAGF.EQ.0)	THEN
	WRITE(24,*) 'WARNING: FREQUENCY INFORMATION DO NOT EXSIST'
	WRITE(24,*) 'VALUE OF Lp MIGHT NOT ACCURATE'
	WRITE(*,*) 'WARNING: FREQUENCY INFORMATION DO NOT EXSIST'
	WRITE(*,*) 'VALUE OF Lp MIGHT NOT ACCURATE'
	END IF
    WRITE(24,*) 'THE NUMBER OF DATA POINTS IS ',NUMIN 
    WRITE(*,*) 'THE NUMBER OF DATA POINTS IS ',NUMIN	  


!==================================================================
!	      FINDING EXPERIMENTAL LOCAL RHEOLOGICAL FEATURE 
!==================================================================


	FQMA=FQ(1)	            	 ! EXPERIMENTAL MAXIMUM G" FREQUECNY 
	FQMI=FQ(NUMIN)				 ! EXPERIMENTAL MINIMUM G" FREQUECNY 
	GGMA=GG(1)					 ! EXPERIMENTAL VALUE OF G' FOR MAXIMUM G"  
	GGGMA=GGG(1)				 ! EXPERIMENTAL VALUE OF MAXIMUM G"
	GGMI=GG(NUMIN)				 ! EXPERIMENTAL VALUE OF G' FOR MINIMUM G" 
	GGGMI=GGG(NUMIN)			 ! EXPERIMENTAL VALUE OF MINIMUM G"

	IDMA=1						 ! INDEX OF DATA POINT FOR MAXIMUM G"
	IDMI=NUMIN					 ! INDEX OF DATA POINT FOR MINIMUM G"
	IDH=NUMIN					 ! INDEX OF DATA POINT FOR REACHING HIGH FREQUECNY REQION


	DO J=2,NUMIN-1
	IF ((GGG(J).GE.GGG(J+1)).AND.(GGG(J).GE.GGG(J-1))) THEN
	IF (GGG(J).GE.GGGMA) THEN	
	FQMA=FQ(J)
	IDMA=J
	GGMA=GG(J)
	GGGMA=GGG(J)
	FLAGR=1
	END IF
	END IF
	IF ((GGG(J).LE.GGG(J+1)).AND.(GGG(J).LE.GGG(J-1))) THEN
	IF (GGG(J).LE.GGGMI) THEN
	FQMI=FQ(J)
	IDMI=J
	GGMI=GG(J)
	GGGMI=GGG(J)
	FLAGMI=1
	CCOR=0.5
	END IF
	END IF
	IF ((FQ(J).GT.10.*FQMI).AND.(FLAGH.EQ.0)) THEN
	IDH=J
	FLAGH=1
	END IF 
	END DO

	IF ((ABS(GGGMA-GGGMI)/GGGMA).LE.0.1) THEN
	FLAGMM=1
	END IF

	IF (FLAGMR.EQ.0) THEN
	DO J=1,NUMIN-1
	IF ((GGG(J+1).LE.GG(J+1)).AND.(GGG(J-1).GE.GG(J-1))) THEN
	FQC=FQ(J)
	END IF
	IF ((GGG(J+1).GE.GG(J+1)).AND.(GGG(J-1).LE.GG(J-1))) THEN
	FQSC=FQ(J)
	END IF
	END DO
	END IF

	IF (FLAGR.EQ.0)	THEN
	DO J=1,NUMIN-1
	IF ((GG(J).LE.GGG(J)).AND.(GG(J+1).GE.GGG(J+1))) THEN
	XCH=J+1
	EXIT
	END IF
	END DO
	FQMA=FQ(XCH)
	GGMA=GG(XCH)
	GGGMA=GGG(XCH)
	FLAGMM=1
	DO J=1,NUMIN
	IF ((FQ(J).GT.100.*FQMA).AND.(FLAGH.EQ.0)) THEN
	IDH=J
 	FLAGH=1
	END IF
	IF ((FQ(J).GT.2.*FQMA).AND.(FLAGMI.EQ.0)) THEN
	IDMI=J
	FQMI=FQ(J)
	GGMI=GG(J)
	GGGMI=GGG(J)
	FLAGMI=1
	END IF
	END DO
	END IF

	IF (FLAGMM.EQ.1) THEN
	DO J=1,NUMIN-1
	IF ((GG(J).GE.GGG(J)).AND.(GG(J+1).LE.GGG(J+1))) THEN
	FQC=FQ(J)
	EXIT
	END IF
	END DO
	END IF

	IF (NUMIN-10.LT.IDMI) THEN
	FLAGMR=1
	END IF

	IF (FLAGF.EQ.1)	THEN
	FMI=FLOOR(LOG10(FQ(1)))+0.D0	     
	FMA=CEILING(LOG10(FQ(NUMIN)))+0.D0	 
	DW=(FMA-FMI)/NUMOU			         
	END IF

	IF (FLAGMI.EQ.0)	THEN
	WRITE(24,*) 'WARNING: G" DO NOT REACH ITS MINIMUM'
	WRITE(24,*) 'CONFIDENCE OF MICELLE LENGTH MIGHT NOT BE GUARANTEED'
	WRITE(*,*) 'WARNING: G" DO NOT REACH ITS MINIMUM'
	WRITE(*,*) 'CONFIDENCE OF MICELLE LENGTH MIGHT NOT BE GUARANTEED'
	END IF
	IF (FLAGH.EQ.0)	THEN
	WRITE(24,*) 'WARNING: EXPERIMENT NOT REACH HIGH FREQUENCY ZONE'
	WRITE(24,*) 'CONFIDENCE OF Lp MIGHT NOT BE GUARANTEED'
	WRITE(*,*) 'WARNING: EXPERIMENT NOT REACH HIGH FREQUENCY ZONE'
	WRITE(*,*) 'CONFIDENCE OF Lp MIGHT NOT BE GUARANTEED'
	END IF
 	IF (FLAGMR.EQ.1) THEN
	WRITE(24,*) 'WARNING: FEW HIGH FREQUENCY DATA'
	WRITE(24,*) 'THEIR CONTRIBUTIONS ARE NEGLECTED'
	WRITE(*,*) 'WARNING: FEW HIGH FREQUENCY DATA'
	WRITE(*,*) 'THEIR CONTRIBUTIONS ARE NEGLECTED'
	END IF
   

!==================================================================
!				           INITIAL GUESSES
!==================================================================
																									 
	G0MA=GGGMA*5.			! THE MAXIMUM ALLOWABLE VALUE OF G0
	G0MI=GGGMA*2.			! THE MINIMUM ALLOWABLE VALUE OF G0
	TT=10**8				! THE LARGEST NUMBER OF TIME STEP
	PUR=3.                  ! RANGE OF ORDER FOR TAO_I IN GA
	PLR=-5.5
					 
	ALPHA=2.				! RATIO OF Le TO Lp

 	IF (FLAGMM.EQ.0) THEN
 	G0=(GGGMA+GGMA)/(0.563-0.1214*LOG10(RATIO))  ! RATIO OF BREAKAGE TIME TO REPTATION TIME
	ELSE
	G0=GGGMA/(0.265-0.0657*LOG10(RATIO))
	END IF
	IF (G0.GE.G0MA) THEN
	G0=G0MA
	END IF
	IF (G0.LE.G0MI)	THEN
	G0=G0MI
	END IF

 	C1=9.75*Kb*TEM/Lp**3./G0
	C2=3.*28./5./PI*Kb*TEM*PHI/d**2./G0/Lp
	DO I=1,50
	IF ((C1*ALPHA**2.2+C2-3.*ALPHA).LT.(APHMI**4.)) THEN
	ALPHA=APHMI
	ELSE
	ALPHA=(C1*ALPHA**2.2+C2-3.*ALPHA)**0.25
	END IF
	END DO
	IF (ALPHA.GE.APHMA) THEN
	ALPHA=APHMA
	END IF
	IF (ALPHA.LE.APHMI)	THEN
	ALPHA=APHMI
	END IF

!   TL=SQRT(ALPHA/2.)	         ! RATIO OF MICELLE LENGTH TO TUBE LENGTH 
!	IF (ALPHA.LT.2.) THEN
!	TL=1.
!	END IF
!	ZETA=ALPHA**0.6*Lp           ! MESH SIZE
!	FIC=2.*PI*Vs/LOG(ZETA/d)	 ! PARALLEL FRICTION COEFFICIENT 
!	D0=Kb*TEM/FIC				 ! MOBILITY OF MICELLE
!	trep=2.*ALPHA**3./FQMA*RATIO**(-2./3.*PCOR)*CCOR	  ! REPTATION TIME
!	IF (trep.GE.trepMA) THEN
!	trep=trepMA
!	END IF
!	IF (trep.LE.trepMI)	THEN
!	trep=trepMI
!	END IF								 
!   Zf1=(trep*D0*(PI*TL)**2.)**(1./3.)/Lp/ALPHA	    ! ENTANGLEMENT NUMBER FOR AVERAGE MICELLE LENGTH

	IF (GGGMA/G0.GE.0.47) THEN	
	IF (RATIO.GT.1) THEN
	CC1=0.85				! CONSTANTS APPEARED IN EMPERICAL FORMULA FOR G"MIN V.S. Z
	P1=-0.22				! POWERS APPEARED IN EMPERICAL FORMULA FOR G"MIN V.S. Z
	ELSE
	IF (RATIO.GT.0.1) THEN
	CC1=0.95
	P1=-0.23
	ELSE 
	IF (RATIO.GT.0.01) THEN
	CC1=1.05
	P1=-0.24
	END IF
	END IF
	END IF
	IF (RATIO.LE.0.01) THEN
	IF (RATIO.LE.0.001)	THEN
	CC1=1.25
	P1=-0.26
	ELSE
	CC1=1.15
	P1=-0.25
	END IF
	END IF									
	Zf=G0/GGGMI*CC1*RATIO**P1	

	ELSE
	IF (ALPHA.GT.1.5) THEN
	IF (Zf.LT.((RATIO/Cb)**(1./Pb))) THEN
	Zf=CC1*RATIO**P1*G0/GGGMI
	ELSE
	CC2=CC1*Cb**(0.25/Pb)*RATIO**(P1-0.25/Pb)
	Zf=(CC2*G0/GGGMI)**(4./3.)
	END IF
	ELSE
	CC2=CC1*Cb**(0.25/Pb)*RATIO**(P1-0.25/Pb)
	Zf=(CC2*G0/GGGMI)**(4./3.)*(ALPHA/1.5)**(-0.55)
	END IF
	END IF

!	Zf=SQRT(Zf*Zf1)


!==================================================================
!				      ITERATION PART
!==================================================================


	JJ=1
	FERR=10.				! THE SUM OF FITTING ERROR FOR ALL FOUR REGIONS
	FERRM=10.				! THE MINIMUM AVERAGE FITTING ERROR FOR ALL FOUR REGIONS DURING ITERATIONS
	PERRM=10.				! THE MINIMUM AVERAGE DIFFERENCE FOR TWO SPECIFIC POINTS (G"MAX, G"MIN)	DURING ITERATIONS
	SERRM1=0				! THE MINIMUM NUMBER OF REGIONS WHOSE FITTING ERROR IS LESS THAN 0.1 DURING ITERATIONS
	SERRM2=0				! THE MINIMUM NUMBER OF SATISIFIED DIFFERNECE DURING ITERATIONS 
	FERRMA=10.
	PERRMA=10.

	RATIOU=RATIOMA			! THE UPPPER BOUNDARY FOR RATIO DURING ITERATIONS
	RATIOL=RATIOMI			! THE LOWER BOUNDARY FOR RATIO DURING ITERATIONS
	LpU=LpMA				! THE UPPPER BOUNDARY FOR lp DURING ITERATIONS
	LpL=LpMI				! THE UPPPER BOUNDARY FOR lp DURING ITERATIONS
	trepU=trepMA			! THE UPPPER BOUNDARY FOR trep DURING ITERATIONS
	trepL=trepMI			! THE UPPPER BOUNDARY FOR trep DURINGE ITERATIONS



	DO WHILE (JJ.LE.NNN)	! ITERATION STARTS

	Lp0=Lp
	d1=0
	d2=0
	G01=0
	Zf1=0
	RATIO1=0
	FLAGPR=0
	FLAGGE=1

	DO I=1,4
	DO J=1,NN+1
	GEP(I,J)=0				     ! NUMBER OF KINK POINTS FOR CERTAIN GA FITTINGS
	END DO
	END DO

	IF (JJ.EQ.NNN) THEN
	Lp=LpF
	d=dF
	ALPHA=ALPHAF
	G0=G0F
	RATIO=RATIOF
	trep=trepF
	Zf=ZfF
	END IF
					         
    III=5*10**5
			 
    TL=SQRT(ALPHA/2.)	         ! RATIO OF MICELLE LENGTH TO TUBE LENGTH 
	IF (ALPHA.LT.2) THEN
	TL=1.
	END IF 
    La=Zf*Lp*ALPHA/TL		     ! AVERAGE TUBE LENGTH

       
	Le=ALPHA*Lp    	             ! ENTANGLEMENT LENGTH 
	ZETA=Le**0.6*Lp**0.4         ! MESH SIZE
	LBAR=La/Lp			         ! RATIO OF TUBE LENGTH TO Lp
	FIC=2.*PI*Vs/LOG(ZETA/d)	 ! PARALLEL FRICTION COEFFICIENT 
	D0=Kb*TEM/FIC				 ! MOBILITY OF MICELLE
    trep=La**3./D0/PI**2.*TL	 ! REPTATION TIME	
	tbr=RATIO*trep				 ! BREAKAGE TIME
    FIC2=4.*PI*Vs/LOG(0.6*ZETA/d)  ! PERPENDICULAR FRICTION COEFFICIENT
	tp=2*Lp**(5./3.)*FIC2/Kb/TEM   ! BENDING TIME
	ST=0.3827*Kb*TEM*tp**0.75/15./PI*4.*d**(-2.)*PHI ! BENDING MODES COEFFICIENT FOR G'
	OS=0.9239/0.3827*ST          ! BENDING MODES COEFFICIENT FOR G"

	SAMPLE=2*NN			         ! SAMPLE SIZE NUMBER 
	tMAX=FLOOR(LOG10(tbr))+PUR 	 ! MAXIMUM VALUE OF TAO_I IN GA
	tMIN=FLOOR(MIN(LOG10(tbr),LOG10(trep*ALPHA/3/LBAR/TL)))+PLR	 ! MINIMUM VALUE OF TAO_I IN GA
	REM=0

	IF (JJ.EQ.NNN) THEN
	GOTO  40
	END IF


	WRITE(20,*) 'ITERATION:',JJ
    WRITE(20,*) 'PLATEAU:',G0
    WRITE(20,*) 'RATIO:',RATIO
	WRITE(20,*)	'Trep:',trep
	WRITE(20,*)	'Zf:',Zf   
	WRITE(20,*) 'MICELLE LENGTH:',La*TL
    WRITE(20,*) 'ALPHA:',ALPHA
    WRITE(20,*) 'PERSISTENCE:',Lp
    WRITE(20,*) 'DIAMETER:',d

	WRITE(*,*) 'ITERATION:',JJ
    WRITE(*,*) 'PLATEAU:',G0
    WRITE(*,*) 'RATIO:',RATIO
	WRITE(*,*)	'Trep:',trep
	WRITE(*,*)	'Zf:',Zf
    WRITE(*,*) 'MICELLE LENGTH:',La*TL
    WRITE(*,*) 'ALPHA:',ALPHA
    WRITE(*,*) 'PERSISTENCE:',Lp
    WRITE(*,*) 'DIAMETER:',d

!==================================================================
!				    LOW FREQUENCY SIMULATION
!==================================================================

	
	DT=tbr/NUM/2.
	IF (DT.GT.DTL) THEN
	DT=DTL
	END IF
	MARK=FLOOR(tbr/DT/NUM/2.)	

20	Dnd=2.*D0*DT/Lp**3./TL
	RLnd=8.*TL/3./PI**1.5
	CONST=2.*(Dnd*TL/3./PI)**0.25
!	CONST=1.

21  DO J=1,10**6				 ! GENERATE MICELLE FOLLOWED BY ITS LENGTH DISTRIBUTION 
	SUM1=0
    DO I=1,10**6
    SUM1=SUM1+CEILING(NUM*J*Lp*EXP(-1.*(1+(I-1)*J)*Lp/La)/La)	
    IF (SUM1.GE.NUM) THEN
    REMAIN=SUM1-NUM
    IF (ABS(REMAIN).LE.1.) THEN
	N=J							 ! INTERVAL OF DISCRETIZED MICELLE TUBE LENGTH
	M=I							 ! MAXIMUM LENGTH IN THE ENSEMBLE
    IF ((I*Lp).GE.La) THEN
    GOTO 22
    END IF 
	END IF
    EXIT
    END IF
    END DO		
    END DO
22  WRITE(24,*) 'LENGTH DISCRETIZATION FINISH'
	WRITE(*,*) 'LENGTH DISCRETIZATION FINISH'


	M=M-REMAIN
	WRITE(24,*) 'THE MINIMUM LENGTH IS',Lp
	WRITE(24,*) 'THE MAXIMUM LENGTH IS',(1+(M-1)*N)*Lp
	WRITE(*,*) 'THE MINIMUM LENGTH IS',Lp
	WRITE(*,*) 'THE MAXIMUM LENGTH IS',(1+(M-1)*N)*Lp


	SUM2=0.
	LSEG=0.
	DO I=1,M
	LENGTH(I,1)=CEILING(NUM*N*Lp*EXP(-1.*(1+(I-1)*N)*Lp/La)/La)
	IF ((I.EQ.M).AND.(SUM2+LENGTH(I,1).GT.NUM)) THEN
	LENGTH(I,1)=LENGTH(I,1)-1
	END IF
	DLENGTH(I,1)=LENGTH(I,1)
	SUM1=1+SUM2
    SUM2=SUM2+LENGTH(I,1)
	LENGTH(I,2)=SUM2
	LSEG=LSEG+(1+(I-1)*N)*LENGTH(I,1)		
	DO J=SUM1,SUM2
	CLIST(J,1)=1.
	LMAP(J,1)=1+(I-1)*N
	DO K=1,INT(CLIST(J,1))
	CLIST(J,K*4-2)=0
	CLIST(J,4*K-1)=0.
	CLIST(J,4*K)=LMAP(J,1)
	CLIST(J,K*4+1)=1.
	END DO
	END DO
	END DO
	DO I=1,M
	LAV(I,1)=0.
	LAV(I,2)=0.
	END DO
	WRITE(24,*) 'CHAIN LIST INITIATION FINISH'
	WRITE(*,*) 'CHAIN LIST INITIATION FINISH'

	KKK=1
	BREATH=LBREATH
	DR=LDR
	NLF=0
	JJJJ=1


	DO KK=1,TT					 ! EVOLUTION OF ENSEMBLE DUE TO RELAXATION AND BREAKAGE 

    OPEN(21,FILE='TEMP.DAT')

	IF (KK.EQ.1) THEN
	KKKK=0
	END IF
		
	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM0'
	END IF

	DO I=1,NUM+NLF				 

	IF (CLIST(I,1).GT.0) THEN	 ! REPATATION
	DL1=SQRT(Dnd/LMAP(I,1))
	CALL RANDOM_NUMBER(RND)

	IF (BREATH.EQ.1) THEN		 ! CLFS
	FL(1)=CLIST(I,2)-CLIST(I,3)
    FL(2)=LMAP(I,1)-CLIST(I,4*INT(CLIST(I,1)))+1.-CLIST(I,4*INT(CLIST(I,1))+1)
	DO K=1,2
	IF (FL(K).EQ.0)	THEN
	CLF(I,2*K-1)=1
	CLF(I,2*K)=0
	END IF
	IF (FL(K).GE.1)	THEN
	CLF(I,2*K-1)=0
	END IF
	END DO
	IF (CLF(I,1).EQ.1)	THEN
	DL2(1)=CONST*((CLF(I,2)+1)**0.25-CLF(I,2)**0.25)
	CLF(I,2)=CLF(I,2)+1
	GOTO 23
	END IF
	RELAX=FL(1)
	DO ITER=1,5
	DL2(1)=SQRT(PI**0.5*Dnd*RLnd/(RELAX**2)+FL(1)**2)-FL(1)
    RELAX=FL(1)+DL2(1)/2.
	END DO	 
23	IF (CLF(I,3).EQ.1) THEN
	DL2(2)=CONST*((CLF(I,4)+1)**0.25-CLF(I,4)**0.25)
	CLF(I,4)=CLF(I,4)+1
	GOTO 24
	END IF
	RELAX=FL(2)
	DO ITER=1,5
	DL2(2)=SQRT(PI**0.5*Dnd*RLnd/(RELAX**2)+FL(2)**2)-FL(2)
	RELAX=FL(2)+DL2(2)/2.
	END DO

24	IF ((CLIST(I,3)-DL2(1)).LE.0) THEN
	CLIST(I,2)=CLIST(I,2)+1
	CLIST(I,3)=CLIST(I,3)-DL2(1)+1.
	GOTO 25
	END IF
	CLIST(I,3)=CLIST(I,3)-DL2(1)
25	IF ((CLIST(I,4*INT(CLIST(I,1))+1)-DL2(2)).LE.0) THEN
	CLIST(I,4*INT(CLIST(I,1)))=CLIST(I,4*INT(CLIST(I,1)))-1
	CLIST(I,4*INT(CLIST(I,1))+1)=CLIST(I,4*INT(CLIST(I,1))+1)-DL2(2)+1.
	GOTO 26
	END IF
	CLIST(I,4*INT(CLIST(I,1))+1)=CLIST(I,4*INT(CLIST(I,1))+1)-DL2(2)
26	FLAG=1

	END IF

	IF (RND.LT.0.5D0) THEN		 ! MOVEMENT OF POINTERS

	DO K=1,INT(CLIST(I,1)) 
	IF ((CLIST(I,4*K-1)-DL1).LT.0) THEN
	CLIST(I,4*K-2)=CLIST(I,4*K-2)+1
	CLIST(I,4*K-1)=CLIST(I,4*K-1)-DL1+1.
	GOTO 27
	END IF
	CLIST(I,4*K-1)=CLIST(I,4*K-1)-DL1
27	IF ((CLIST(I,4*K+1)+DL1).GT.1) THEN
	CLIST(I,4*K)=CLIST(I,4*K)+1
	CLIST(I,4*K+1)=CLIST(I,4*K+1)+DL1-1.
	IF (CLIST(I,4*K).GT.LMAP(I,1)) THEN
	CLIST(I,4*K)=LMAP(I,1)
	CLIST(I,4*K+1)=1.
    END IF
	GOTO 28
	END IF
	CLIST(I,4*K+1)=CLIST(I,4*K+1)+DL1
28	FLAG=1
	END DO

	ELSE

	DO K=1,INT(CLIST(I,1)) 
	IF ((CLIST(I,4*K+1)-DL1).LE.0) THEN
	CLIST(I,4*K)=CLIST(I,4*K)-1
	CLIST(I,4*K+1)=CLIST(I,4*K+1)-DL1+1.
	GOTO 29
	END IF
	CLIST(I,4*K+1)=CLIST(I,4*K+1)-DL1
29	IF ((CLIST(I,4*K-1)+DL1).GE.1) THEN
	CLIST(I,4*K-2)=CLIST(I,4*K-2)-1
	CLIST(I,4*K-1)=CLIST(I,4*K-1)+DL1-1.
	IF (CLIST(I,4*K-2).LT.1)	THEN
	CLIST(I,4*K-2)=0
	CLIST(I,4*K-1)=0.
    END IF
	GOTO 30
	END IF
	CLIST(I,4*K-1)=CLIST(I,4*K-1)+DL1
30	FLAG=1
	END DO

	END IF

	END IF

	DO K=1,INT(CLIST(I,1))		  ! ANNILATION OF POINTERS
	IF (CLIST(I,1).GT.0) THEN
	IF (CLIST(I,4*K-2).GT.CLIST(I,4*K)) THEN
    DO II=K,INT(CLIST(I,1)-1)
	CLIST(I,4*II-2)=CLIST(I,4*(II+1)-2)
	CLIST(I,4*II-1)=CLIST(I,4*(II+1)-1)
	CLIST(I,4*II)=CLIST(I,4*(II+1))
	CLIST(I,4*II+1)=CLIST(I,4*(II+1)+1)
	END DO
	CLIST(I,1)=CLIST(I,1)-1
	END IF
	IF ((CLIST(I,4*K).GT.CLIST(I,4*K+2)).AND.(K.LT.CLIST(I,1))) THEN
    DO II=K,INT(CLIST(I,1)-2)
	CLIST(I,4*II)=CLIST(I,4*(II+1))
	CLIST(I,4*II+1)=CLIST(I,4*(II+1)+1)
	CLIST(I,4*II+2)=CLIST(I,4*(II+1)+2)
	CLIST(I,4*II+3)=CLIST(I,4*(II+1)+3)
	END DO
	CLIST(I,4*INT(CLIST(I,1)-1))=CLIST(I,4*INT(CLIST(I,1)))
	CLIST(I,4*INT(CLIST(I,1)-1)+1)=CLIST(I,4*INT(CLIST(I,1))+1)
	CLIST(I,1)=CLIST(I,1)-1
	END IF
	IF ((CLIST(I,4*K-2).EQ.CLIST(I,4*K)).AND.((CLIST(I,4*K-1)+CLIST(I,4*K+1)).LE.1.)) THEN
	DO II=K,INT(CLIST(I,1)-1)
	CLIST(I,4*II-2)=CLIST(I,4*(II+1)-2)
	CLIST(I,4*II-1)=CLIST(I,4*(II+1)-1)
	CLIST(I,4*II)=CLIST(I,4*(II+1))
	CLIST(I,4*II+1)=CLIST(I,4*(II+1)+1)
	END DO
	CLIST(I,1)=CLIST(I,1)-1
	END IF
	IF ((CLIST(I,4*K).EQ.CLIST(I,4*K+2)).AND.(K.LT.CLIST(I,1)).AND.((CLIST(I,4*K)+CLIST(I,4*K+2)).GE.1.)) THEN
    DO II=K,INT(CLIST(I,1)-2)
	CLIST(I,4*II)=CLIST(I,4*(II+1))
	CLIST(I,4*II+1)=CLIST(I,4*(II+1)+1)
	CLIST(I,4*II+2)=CLIST(I,4*(II+1)+2)
	CLIST(I,4*II+3)=CLIST(I,4*(II+1)+3)
	END DO
	CLIST(I,4*INT(CLIST(I,1)-1))=CLIST(I,4*INT(CLIST(I,1)))
	CLIST(I,4*INT(CLIST(I,1)-1)+1)=CLIST(I,4*INT(CLIST(I,1))+1)
	CLIST(I,1)=CLIST(I,1)-1
	END IF
	END IF
	END DO

	END DO

	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM1'
	END IF

	IF (KK.GT.MARK*KKKK) THEN		! BREAKAGE AND REJOINING OCCURS
	KKKK=KKKK+1
    
    CALL RANDOM_NUMBER(BR)			! BREAKAGE 
	
	IF ((BR.LT.0.5D0).OR.(NLF.LE.NLFL)) THEN

31  CALL RANDOM_NUMBER(RND)
	LBR=INT(RND*LSEG)
	IF (LBR.LT.1) THEN
	GOTO 31
	END IF
	DO I=1,(NUM+NLF)
	LBR=LBR-LMAP(I,1)
	IF (LBR.EQ.0) THEN
	GOTO 31
	END IF			
	IF (LBR.LT.0) THEN
	LBR=LBR+LMAP(I,1)
	LPI1(1)=I
	IF (LMAP(I,1).EQ.1) THEN
	GOTO 31
	END IF
	GOTO 32
	END IF
	END DO
	

32	CALL RANDOM_NUMBER(RND)
    IF (RND.LE.0.5) THEN
	LSI=-1
	ELSE
	LSI=0
	END IF
	IF (LBR.EQ.1) THEN
	LSI=0
	END IF


 	NEWL1=LBR+LSI
	NEWL2=LMAP(LPI1(1),1)-NEWL1


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM2'
	END IF


	IF (CLIST(LPI1(1),1).EQ.0) THEN
	CLIST(NUM+NLF+1,1)=0
	LMAP(NUM+NLF+1,1)=NEWL1
	CLIST(NUM+NLF+2,1)=0
	LMAP(NUM+NLF+2,1)=NEWL2
	END IF

	IF (CLIST(LPI1(1),1).GT.0) THEN
	ICOUNT=0
	DO I=1,INT(CLIST(LPI1(1),1)*2)
	IF (CLIST(LPI1(1),2*I).LE.NEWL1) THEN
	ICOUNT=ICOUNT+1
	END IF
	END DO

	IF (MOD(ICOUNT,2).EQ.0) THEN

	CLIST(NUM+NLF+1,1)=ICOUNT/2
	LMAP(NUM+NLF+1,1)=NEWL1
	IF (CLIST(NUM+NLF+1,1).GT.0) THEN
	DO K=2,INT(4*CLIST(NUM+NLF+1,1)+1)
	CLIST(NUM+NLF+1,K)=CLIST(LPI1(1),K)
	END DO
	END IF
		
	CLIST(NUM+NLF+2,1)=CLIST(LPI1(1),1)-ICOUNT/2
	LMAP(NUM+NLF+2,1)=NEWL2
	IF (CLIST(NUM+NLF+2,1).GT.0) THEN
	DO K=INT(CLIST(NUM+NLF+1,1)+1),INT(CLIST(LPI1(1),1))
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1)))-2)=CLIST(LPI1(1),4*K-2)-NEWL1
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1)))-1)=CLIST(LPI1(1),4*K-1)
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1))))=CLIST(LPI1(1),4*K)-NEWL1
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1)))+1)=CLIST(LPI1(1),4*K+1)
	END DO
	END IF

	ELSE
	CLIST(NUM+NLF+1,1)=(ICOUNT+1)/2
	LMAP(NUM+NLF+1,1)=NEWL1
	IF (CLIST(NUM+NLF+1,1).GT.0) THEN
 	DO K=2,INT(4*CLIST(NUM+NLF+1,1)+1)
	CLIST(NUM+NLF+1,K)=CLIST(LPI1(1),K)
	END DO
	CLIST(NUM+NLF+1,4*INT(CLIST(NUM+NLF+1,1)))=NEWL1
    CLIST(NUM+NLF+1,4*INT(CLIST(NUM+NLF+1,1))+1)=1.
	END IF

	CLIST(NUM+NLF+2,1)=CLIST(LPI1(1),1)-(ICOUNT-1)/2
	LMAP(NUM+NLF+2,1)=NEWL2
	IF (CLIST(NUM+NLF+2,1).GT.0) THEN
	CLIST(NUM+NLF+2,2)=0
	CLIST(NUM+NLF+2,3)=0.
	DO K=INT(CLIST(NUM+NLF+1,1)),INT(CLIST(LPI1(1),1))
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1))+1))=CLIST(LPI1(1),4*K)-NEWL1
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1))+1)+1)=CLIST(LPI1(1),4*K+1)
	IF (K.LT.CLIST(LPI1(1),1)) THEN
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1))+1)+2)=CLIST(LPI1(1),4*K+2)-NEWL1
	CLIST(NUM+NLF+2,4*(K-INT(CLIST(NUM+NLF+1,1))+1)+3)=CLIST(LPI1(1),4*K+3)
	END IF
	END DO
	END IF

	END IF

	END IF

	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM3'
	END IF

	DO I=LPI1(1),NUM+NLF+1
	LMAP(I,1)=LMAP(I+1,1)
	DO J=1,4*INT(CLIST(I+1,1))+1
	CLIST(I,J)=CLIST(I+1,J)
	END DO
	END DO
	IF (MOD(KK,III).EQ.0) THEN
	WRITE(24,*) 'CHAIN BREAKAGE OCCUR:',KK
	WRITE(*,*) 'CHAIN BREAKAGE OCCUR:',KK
	END IF
	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM4'
	END IF


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM5'
	END IF
	NLF=NLF+1

	END IF


	IF ((BR.GT.0.5D0).OR.(NLF.GE.NLFU)) THEN	! REJOINING

33  CALL RANDOM_NUMBER(RND)
	LREC1=INT(RND*(NUM+NLF))
	IF (LREC1.LT.1) THEN
	GOTO 33
	END IF
	LPI1(1)=LREC1
34  CALL RANDOM_NUMBER(RND)
	LREC2=INT(RND*(NUM+NLF))
	IF (LREC2.LT.1) THEN
	GOTO 34
	END IF
	LPI1(2)=LREC2
	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) LREC1,LREC2
	END IF

	IF (LPI1(2).EQ.LPI1(1)) THEN
	GOTO 33
	END IF
	IF ((LMAP(LPI1(1),1)+LMAP(LPI1(2),1)).GT.M) THEN
    GOTO 33
	END IF

 	NEWL1=LMAP(LPI1(1),1)
	NEWL2=LMAP(LPI1(2),1)


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM6'
	END IF


	CLIST(NUM+NLF+1,1)=CLIST(LPI1(1),1)+CLIST(LPI1(2),1)
	LMAP(NUM+NLF+1,1)=NEWL1+NEWL2
	IF (CLIST(LPI1(1),1).GT.0) THEN	
	DO K=2,INT(4*CLIST(LPI1(1),1)+1)
	CLIST(NUM+NLF+1,K)=CLIST(LPI1(1),K)
	END DO
	END IF
	IF (CLIST(LPI1(2),1).GT.0) THEN
	DO K=1,INT(CLIST(LPI1(2),1))
	CLIST(NUM+NLF+1,4*(K+INT(CLIST(LPI1(1),1)))-2)=CLIST(LPI1(2),4*K-2)+NEWL1
	CLIST(NUM+NLF+1,4*(K+INT(CLIST(LPI1(1),1)))-1)=CLIST(LPI1(2),4*K-1)
	CLIST(NUM+NLF+1,4*(K+INT(CLIST(LPI1(1),1))))=CLIST(LPI1(2),4*K)+NEWL1
	CLIST(NUM+NLF+1,4*(K+INT(CLIST(LPI1(1),1)))+1)=CLIST(LPI1(2),4*K+1)
	END DO
	END IF

	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM7'
	END IF

	IF (LPI1(1).LT.LPI1(2)) THEN
	DO I=LPI1(1),NUM+NLF
	LMAP(I,1)=LMAP(I+1,1)
	DO J=1,4*INT(CLIST(I+1,1))+1
	CLIST(I,J)=CLIST(I+1,J)
	END DO
	END DO
	DO I=(LPI1(2)-1),NUM+NLF-1
	LMAP(I,1)=LMAP(I+1,1)
	DO J=1,INT(4*CLIST(I+1,1)+1)
	CLIST(I,J)=CLIST(I+1,J)
	END DO
	END DO
	ELSE
	DO I=LPI1(1),NUM+NLF
	LMAP(I,1)=LMAP(I+1,1)
	DO J=1,INT(4*CLIST(I+1,1)+1)
	CLIST(I,J)=CLIST(I+1,J)
	END DO
	END DO
	DO I=LPI1(2),NUM+NLF-1
	LMAP(I,1)=LMAP(I+1,1)
	DO J=1,INT(4*CLIST(I+1,1)+1)
	CLIST(I,J)=CLIST(I+1,J)
	END DO
	END DO
	END IF		
		
    IF (MOD(KK,III).EQ.0) THEN
	WRITE(24,*) 'CHAIN RECOMBATION OCCUR:',KK
	WRITE(*,*) 'CHAIN RECOMBATION OCCUR:',KK
	END IF


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM8'
    WRITE(*,*) 'NO PROBLEM8'
	END IF
	NLF=NLF-1

	END IF


	SUM2=0.
	DO I=1,M
	LENGTH(I,1)=0
	DO J=1,NUM+NLF
    IF (LMAP(J,1).EQ.((I-1)*N+1)) THEN
	LENGTH(I,1)=LENGTH(I,1)+1
	END IF
	END DO
	SUM2=SUM2+LENGTH(I,1)
	LENGTH(I,2)=SUM2
	END DO
	IF (MOD(KK,III).EQ.0) THEN
	WRITE(24,*) 'LENGTH LIST SUMMATION FINISH'
	WRITE(*,*) 'LENGTH LIST SUMMATION FINISH'
	END IF

	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM9'
    WRITE(*,*) 'NO PROBLEM9'
	END IF

	END IF

	G1=0.							! CALCULATE STRESS RELAXATION FUNCTION
	DO I=1,NUM+NLF
	IF (CLIST(I,1).GT.0) THEN
	DO K=1,INT(CLIST(I,1))
	G1=G1+(CLIST(I,4*K)-CLIST(I,4*K-2)+CLIST(I,4*K-1)+CLIST(I,4*K+1)-1.)/LSEG
	END DO
	END IF
	END DO
	IF (DR.EQ.1) THEN
	G2=G1**2
	ELSE
	G2=G1
	END IF

	IF (KKK.EQ.1) THEN			   ! WRITTING TIME DOMAIN DATA IN THE TEMPORARY FILE
  	WRITE(21,*) 0,0.,1.
	KKK=KKK+1
	END IF

	IF (KK.LE.49) THEN
    WRITE(21,*)	KK,KK*DT,G2
	KKK=KKK+1
	ELSE
	IF ((KKK.LE.100).AND.(MOD(KK,5).EQ.0)) THEN
	WRITE(21,*) KK,KK*DT,G2
    KKK=KKK+1
	ELSE
	IF ((KKK.LE.200).AND.(MOD(KK,20).EQ.0)) THEN
	WRITE(21,*) KK,KK*DT,G2
	KKK=KKK+1
	ELSE
	IF (MOD(KK,200).EQ.0) THEN
	WRITE(21,*) KK,KK*DT,G2
	KKK=KKK+1
	END IF
	END IF
	END IF
	END IF

	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM10'
	END IF


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) 'NO PROBLEM11'
	END IF

	IF (MOD(KK,III).EQ.0) THEN
	WRITE(24,*) KK,NLF,G2
	WRITE(*,*) KK,NLF,G2
	END IF

	IF (G2.LT.0.001) THEN
	REM=KK
	WRITE(21,*)	-1,KK*DT,G2
	WRITE(*,*) 'KK',KK
	WRITE(24,*)	'KK',KK
	CLOSE(21)
	EXIT
	END IF


	IF (MOD(KK,III).EQ.0) THEN
	WRITE(24,*) KK,'REPTATION FINISH'
	WRITE(*,*) KK,'REPTATION FINISH'
	END IF


	IF (KK.EQ.JJJ) THEN
	WRITE(24,*) NUM+NLF
	OPEN(14,FILE='TEST1.DAT') 
    DO I=1,NUM+NLF
	WRITE(14,*) I,CLIST(I,1),LMAP(I,1)
	DO K=1,2*INT(CLIST(I,1))
	WRITE(14,*) CLIST(I,2*K),CLIST(I,2*K+1)
    END DO
	END DO
	CLOSE(14)
	OPEN(15,FILE='TEST2.DAT') 
    DO I=1,M
	WRITE(15,*) I,LENGTH(I,1),LENGTH(I,2)
	END DO
	CLOSE(15)
	END IF


	END DO


	DO I=4,9
    IF (REM/10.**I.LT.1.) THEN 
	XCH=FLOOR(REM/10.**(I-1.))
	REM=XCH*10.**(I-1.)+CEILING((REM-XCH*10.**(I-1.))/10.**(I-2.))*10.**(I-2.)
	GOTO 42
	END IF
	END DO

42	WRITE(*,*) 'REM',REM
	WRITE(24,*)	'REM',REM

	INDEX=(REM/40000.)**(1./3.)
    OPEN(22,FILE='TEMP.DAT')

	DO J=1,700			! PICK APPROPRIATE NUMBER OF THE DATA FROM TEMPORARY FILE 

	IF (JJJJ.LE.300) THEN
	READ(22,*,END=41) KK,T(JJJJ),G(JJJJ)
	JJJJ=JJJJ+1

	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END IF

	IF ((JJJJ.GT.300).AND.(JJJJ.LE.400)) THEN
	DO I=1,INT(INDEX-1.)
	READ(22,*,END=41) KK
 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END DO

	READ(22,*,END=41) KK,T(JJJJ),G(JJJJ)
 	JJJJ=JJJJ+1

 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END IF

	IF ((JJJJ.GT.400).AND.(JJJJ.LE.500)) THEN
	DO I=1,INT(INDEX**2.-1.)
	READ(22,*,END=41) KK
 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END DO

	READ(22,*,END=41) KK,T(JJJJ),G(JJJJ)
 	JJJJ=JJJJ+1

 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END IF

	IF (JJJJ.GT.500) THEN
	DO I=1,INT(INDEX**3.-1.)
	READ(22,*,END=41) KK
 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END DO

	READ(22,*,END=41) KK,T(JJJJ),G(JJJJ)
 	JJJJ=JJJJ+1

 	IF (KK.LT.0) THEN
	GOTO 41
	END IF
	END IF

	END DO


41	CLOSE(22)
	NUMG=JJJJ-1
    WRITE(*,*) 'INITIATION OF GA FINISHED'
	WRITE(24,*) 'INITIATION OF GA FINISHED'

	DO I=1,M
	DO J=1,2
	LAV(I,J)=LAV(I,J)+LENGTH(I,J)
	END DO
	END DO

	SUM2=0.
	DO I=1,M
	LENGTH(I,1)=CEILING(NUM*N*Lp*EXP(-1.*(1+(I-1)*N)*Lp/La)/La)
	SUM1=1+SUM2
    SUM2=SUM2+LENGTH(I,1)
	LENGTH(I,2)=SUM2		
	DO J=SUM1,SUM2
	CLIST(J,1)=1
	LMAP(J,1)=1+(I-1)*N
	DO K=1,INT(CLIST(J,1))
	CLIST(J,K*4-2)=0
	CLIST(J,4*K-1)=0.
	CLIST(J,4*K)=1+(I-1)*N
	CLIST(J,K*4+1)=1.
	END DO
	END DO
	END DO

	IF (OUTGT.EQ.1)	THEN
	OPEN(3,FILE='G_t.DAT')	          ! WRITE OUTPUT FILE FOR NORMALIZED G(t) 
	WRITE(3,*) 'LOOP',JJ
	WRITE(3,*) 'PARAMETERS PART'
	WRITE(3,*) 'RATIO',RATIO
	WRITE(3,*) 'TIME INTERVAL',DT	
	WRITE(3,*) 'MICELLE LENGTH',LBAR*TL 	
    WRITE(3,*) 'PLATAEU',G0
 	WRITE(3,*) 'Le',Le 
    WRITE(3,*) 'Lp',Lp    
 	WRITE(3,*) 'DATA PART'
    DO I=1,NUMG
 	WRITE(3,*) T(I),G(I)
    END DO
	CLOSE(3)
	END IF

	IF (OUTL.EQ.1) THEN
	OPEN(4,FILE='L_DIS.DAT') 		 ! WRITE OUPTPUT FILE FOR MICELLE LENGTH DISTRIBUTION IN THE ENSEMBEL
    DO I=1,M
 	WRITE(4,*) I,LAV(I,1),LAV(I,2)
    END DO
  	CLOSE(4) 
	END IF

!==================================================================
!				        GENETIC ALGORITHM
!==================================================================
	
	DO WHILE (FLAGGE.LE.2)


	IF (tMAX.GT.TERM) THEN
	tMAX=INT(TERM)+INT(2.*(TERM-INT(TERM)))*0.5
	END IF

	DO I=1,SAMPLE			  ! GENERATE RANDOM ENSEMBLE FOR GA FITTING PARAMETERS
	DO J=1,NN      
35  CALL RANDOM_NUMBER(RND)
	A(I,J)=RND*9.+1.
	IF (A(I,J).GE.10.) THEN
	GOTO 35
	END IF
	CALL RANDOM_NUMBER(RND)
	B(I,J)=FLOOR((RND-1.)*5.)
	INDEX1=(tMAX-tMIN)/NN*(J-1)+tMIN
	INDEX2=(tMAX-tMIN)/NN*J+tMIN
	IF (FLAGG.EQ.0)	THEN
	CALL RANDOM_NUMBER(RND)
	TAO(I,J)=10.**((INDEX2-INDEX1)*RND+INDEX1)
	ELSE
	TAO(I,J)=TAGET_TAO(J) 
	END IF
	END DO
	END DO

	OPT1=10.**10.
	OPTK1=20.

	DO II=1,GENERATION 		! EVOLUATION OF THE FITTING ENSEMBLE 

	DO I=1,SAMPLE			! NORMALIZE THE FITTING ENSEMBLE 

	RESCALE=1
	CHECK=1

	DO WHILE ((CHECK+RESCALE).NE.0)

	CALL RANDOM_NUMBER(RND)
	DO J=1,POINT-1
	IF (ABS(B(I,POINT+1-J)-B(I,POINT-J)).GT.1) THEN
	RESCALE=1
	CALL RANDOM_NUMBER(RND)
	B(I,POINT-J)=NINT(RND*2.5-1.25)+B(I,POINT+1-J)
	END IF
	END DO
	DO J=POINT,NN-1
	IF (ABS(B(I,J)-B(I,J+1)).GT.1) THEN
	RESCALE=1
	CALL RANDOM_NUMBER(RND)
	B(I,J+1)=NINT(RND*2.5-1.25)+B(I,J)
	END IF
	END DO
	CHECK=0	
	
	SCALE=0.
	DO J=1,NN
	SCALE=SCALE+A(I,J)*10.**B(I,J)
	END DO
	IF (ABS(SCALE-1.).LT.0.0001) THEN
	GOTO 36
	END IF
	DO J=1,NN
	A(I,J)=A(I,J)/SCALE
	DO WHILE (A(I,J).LT.1.)
	CHECK=1
	A(I,J)=10.*A(I,J)
	B(I,J)=B(I,J)-1
	END DO
	DO WHILE (A(I,J).GE.10.)
	CHECK=1
	A(I,J)=A(I,J)/10.
	B(I,J)=B(I,J)+1
	END DO
	END DO
36	RESCALE=0

	END DO

  	END DO

	IF (JJJ.NE.0) THEN
	OPEN(11,FILE='TEST3.DAT') 
	DO I=1,SAMPLE
	DO J=1,NN
    WRITE(11,*) J,A(I,J),B(I,J),TAO(I,J)
	END DO
	END DO
	CLOSE(11)
	END IF

	DO J=1,SAMPLE		! CALCULATE THE FITNESS 
	ERR(J)=0.
	DO K=1,NUMG
	GF(K)=0.
	DO I=1,NN
	IF (T(K)/TAO(J,I).GT.500.) THEN
	GF(K)=GF(K)+0.
	ELSE
	IF (T(K)/TAO(J,I).LT.0.001)	THEN
 	GF(K)=GF(K)+A(J,I)*10.**(B(J,I))
	ELSE
	GF(K)=GF(K)+A(J,I)*10.**(B(J,I))*EXP(-1.*T(K)/TAO(J,I))
	END IF
	END IF
	END DO
	ERR(J)=ERR(J)+ABS(G(K)-GF(K))
	END DO
	END DO

	DO I=1,(SAMPLE-1)		  ! REORDER THE ENSEMBLE BASED ON THE FITNESS 
	MINI=ERR(I)
	XCH=I
	DO J=I,SAMPLE
	IF (ERR(J).LT.MINI) THEN
	MINI=ERR(J)
	ERR(J)=ERR(I)
	ERR(I)=MINI
	XCH=J
	END IF
	END DO
	IF (I.EQ.1) THEN
	OPT2=MINI
	END IF
	DO K=1,NN
	XCH1(K)=A(I,K)
	A(I,K)=A(XCH,K)
	A(XCH,K)=XCH1(K)
	XCH1(K)=B(I,K)
	B(I,K)=B(XCH,K)
	B(XCH,K)=XCH1(K)
	XCH1(K)=TAO(I,K)
	TAO(I,K)=TAO(XCH,K)
	TAO(XCH,K)=XCH1(K)
	END DO
	END DO

	DO I=1,5				 ! CALCULATE NUMBER OF KINK POINTS FOR TOP FIVE
	GEN(1,I)=0
	GEN(2,I)=0
	GEN(3,I)=1
	GEN(4,I)=NN
	FLAG=0
 	DO K=2,NN
	IF ((B(I,K-1).GT.-4).AND.(B(I,K).EQ.-4)) THEN
	GEN(1,I)=GEN(1,I)+1
	IF (FLAG.EQ.1) THEN
	GEN(4,I)=K
	END IF
	END IF
	IF ((B(I,K-1).EQ.-4).AND.(B(I,K).GT.-4)) THEN
	GEN(2,I)=GEN(2,I)+1
	IF (FLAG.EQ.0) THEN
	GEN(3,I)=K-1
	FLAG=1
	END IF
	END IF
	END DO
	END DO

	I=1
	DO J=1,5
	IF (LOG(ERR(J)/ERR(1)).LT.0.025) THEN
	IF ((GEN(1,J).LT.GEN(1,1)).AND.(GEN(2,J).LT.GEN(2,1))) THEN
	MINI=GEN(1,J)
	GEN(1,J)=GEN(1,1)
	GEN(1,1)=MINI
	MINI=GEN(2,J)
	GEN(2,J)=GEN(2,1)
	GEN(2,1)=MINI
	OPT2=ERR(J)
	OPTK2=GEN(1,1)+GEN(2,1)
	I=J
	END IF
	IF ((GEN(1,J).EQ.GEN(1,1)).AND.(GEN(2,J).EQ.GEN(2,1))) THEN
	IF ((GEN(4,J)-GEN(3,J)).GT.(GEN(4,1)-GEN(3,1))) THEN
 	MINI=GEN(1,J)
	GEN(1,J)=GEN(1,1)								
	GEN(1,1)=MINI
	MINI=GEN(2,J)
	GEN(2,J)=GEN(2,1)
	GEN(2,1)=MINI
	OPT2=ERR(J)
	OPTK2=GEN(1,1)+GEN(2,1)
	I=J
	END IF
	END IF
	END IF
	END DO


	IF ((OPT2.LT.OPT1).OR.((LOG(OPT2/OPT1).LT.0.025).AND.(OPTK2.LT.OPTK1))) THEN
	OPT1=OPT2
	OPTK1=OPTK2
	DO K=1,NN
	TAGET_A(K)=A(I,K)
	TAGET_B(K)=B(I,K)
	TAGET_TAO(K)=TAO(I,K)
	END DO
	END IF
	IF (OPT1.LE.0.1) THEN
	GOTO 37
	END IF

	DO I=(SAMPLE/2+1),(3*SAMPLE/4)	   ! KEEP THE ELITES
	DO J=1,NN
	A(I,J)=A(I-SAMPLE/2,J)
	B(I,J)=B(I-SAMPLE/2,J)
	TAO(I,J)=TAO(I-SAMPLE/2,J)
	END DO
	END DO

	DO I=1,(SAMPLE/4) 				  ! CROSS-OVER 
	CALL RANDOM_NUMBER(RND)
	IF (RND.LE.PC) THEN
	CALL RANDOM_NUMBER(RND)
	POINT=CEILING(RND*NN)
	DO J=POINT,NN
	XCH1(J)=A(2*I-1,J)
	A(2*I-1,J)=A(2*I,J)
	A(2*I,J)=XCH1(J)
	XCH1(J)=B(2*I-1,J)
	B(2*I-1,J)=B(2*I,J)
	B(2*I,J)=XCH1(J)
	XCH1(J)=TAO(2*I-1,J)
	TAO(2*I-1,J)=TAO(2*I,J)
	TAO(2*I,J)=XCH1(J)
	END DO
	END IF
	END DO


	DO I=1,(3*SAMPLE/4)				  ! MUTATION
	DO J=1,NN
	CALL RANDOM_NUMBER(RND)
	IF (RND.LE.PM) THEN
38	CALL RANDOM_NUMBER(RND)
	A(I,J)=RND*9.+1.
	IF (A(I,J).GE.10.) THEN
	GOTO 38
	END IF
	END IF
	CALL RANDOM_NUMBER(RND)
	IF (RND.LE.PM) THEN
	CALL RANDOM_NUMBER(RND)
	IF (J.EQ.1)	THEN
	B(I,J)=B(I,J+1)+NINT(RND*2.5-1.25)
	ELSE 
	IF (J.EQ.NN) THEN
	B(I,J)=B(I,J-1)+NINT(RND*2.5-1.25)
	ELSE
	B(I,J)=B(I,J+1)+NINT(RND*(B(I,J-1)-B(I,J+1)))
	END IF
	END IF
	END IF
	IF (FLAGG.EQ.0) THEN
	CALL RANDOM_NUMBER(RND)
	IF (RND.LE.PM) THEN
	INDEX1=(tMAX-tMIN)/20.*(J-1)+tMIN
	INDEX2=(tMAX-tMIN)/20.*J+tMIN
	CALL RANDOM_NUMBER(RND)
	TAO(I,J)=10.**((INDEX2-INDEX1)*RND+INDEX1)
	END IF
	END IF
	END DO
	END DO

	DO I=(3*SAMPLE/4)+1,SAMPLE		! SELECTION 
	DO J=1,NN
39	CALL RANDOM_NUMBER(RND)
	A(I,J)=RND*9.+1.
	IF (A(I,J).GE.10.) THEN
	GOTO 39
	END IF
	IF (FLAGG.EQ.0) THEN
	INDEX1=(tMAX-tMIN)/20.*(J-1)+tMIN
	INDEX2=(tMAX-tMIN)/20.*J+tMIN
	CALL RANDOM_NUMBER(RND)
	TAO(I,J)=10.**((INDEX2-INDEX1)*RND+INDEX1)
	END IF
	CALL RANDOM_NUMBER(RND)
	B(I,J)=FLOOR((RND-1.)*5.)
	END DO
	END DO

	IF (MOD(II,5000).EQ.0) THEN
	WRITE(24,*) II,' GENERATION FINISH',OPT1
	WRITE(*,*) II,' GENERATION FINISH',OPT1
	END IF

	END DO

	DO K=2,NN
	IF ((TAGET_B(K-1).GT.-4).AND.(TAGET_B(K).EQ.-4)) THEN
	GEP(1,K-1)=1
	GEP(1,NN+1)=GEP(1,NN+1)+1
	END IF
	IF ((TAGET_B(K-1).EQ.-4).AND.(TAGET_B(K).GT.-4)) THEN
	GEP(2,K)=-1
	GEP(2,NN+1)=GEP(2,NN+1)+1
	END IF
	END DO
	DO J=1,NN-1
	IF ((TAGET_B(NN+1-J).GT.-4).AND.(TAGET_B(NN-J).EQ.-4)) THEN
	GEP(3,NN+1-J)=1
	GEP(3,NN+1)=GEP(3,NN+1)+1
	END IF
	IF ((TAGET_B(NN+1-J).EQ.-4).AND.(TAGET_B(NN-J).GT.-4)) THEN
	GEP(4,NN-J)=-1
	GEP(4,NN+1)=GEP(4,NN+1)+1
	END IF
	END DO

	WRITE(23,*)	'ITERATION:',JJ
	DO I=1,NN
	WRITE(23,*) TAGET_A(I)*10.**TAGET_B(I),TAGET_TAO(I)
	WRITE(*,*) TAGET_A(I)*10.**TAGET_B(I),TAGET_TAO(I)
	END DO

	SUM=0.
	DO I=1,NUMG
	SUM=SUM+G(I)
	END DO
    WRITE(23,*) 'AVERAGE ERROR IS',OPT1/SUM
    WRITE(24,*) 'AVERAGE ERROR IS',OPT1/SUM
    WRITE(*,*) 'AVERAGE ERROR IS',OPT1/SUM


	IF (FLAGGE.EQ.1) THEN		! REDO THE GA IF TOO MANY KINK POINTS OR TOO LARGE FITTING ERROR 


	IF ((GEP(1,NN+1).EQ.1).AND.(GEP(2,NN+1).EQ.1)) THEN	
	DO I=1,NN
	IF (GEP(1,I).EQ.1) THEN
	J=I
	END IF
	IF (GEP(2,I).EQ.-1) THEN
	K=I
	END IF
	END DO

	IF (((NN-J).LE.2).AND.((K-1).LE.2).AND.(OPT1/SUM.LE.0.0065)) THEN
	FLAGGE=FLAGGE+1
	GOTO 51
	
	ELSE
	IF (J.LE.K)	THEN
	IF (K.LE.NN/2) THEN
	DISP=MAX(MOD((K-2),2),0)*0.5
 	PLR=PLR+DISP
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).GT.-5) THEN
	PUR=PUR+1.
	ELSE
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).EQ.-5) THEN
	PUR=PUR+0.5
	END IF
	END IF
	ELSE
  	DISP=MAX(MOD((NN-1-J),2),0)*0.5
	PUR=PUR-DISP
	IF ((TAGET_B(1)+TAGET_B(2)).LT.-5) THEN
	PLR=PLR-0.5
	ELSE
	IF ((TAGET_B(1)+TAGET_B(2)).EQ.-5) THEN
	PLR=PLR-1.
	ELSE
	PLR=PLR-1.5
	END IF
	END IF
	END IF
	END IF

	IF (J.GT.K) THEN
    DISP=MAX(MOD((K-2),2),0)*0.5
	PLR=PLR+DISP
	DISP=MAX(MOD((NN-1-J),2),0)*0.5
	PUR=PUR-DISP
	END IF

	END IF
	END IF

	IF ((GEP(1,NN+1).EQ.0).AND.(GEP(2,NN+1).EQ.0)) THEN

 	IF (OPT1/SUM.LT.0.0065)	THEN
	FLAGGE=FLAGGE+1
	GOTO 51
	END IF

	IF ((TAGET_B(NN)+TAGET_B(NN-1)).GT.-5) THEN
	PUR=PUR+1.
	ELSE
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).EQ.-5) THEN
	PUR=PUR+0.5
	END IF
	END IF
	IF ((TAGET_B(1)+TAGET_B(2)).LT.-5) THEN
	PLR=PLR-0.5
	ELSE
	IF ((TAGET_B(1)+TAGET_B(2)).EQ.-5) THEN
	PLR=PLR-1.
	ELSE
	PLR=PLR-1.5
	END IF
	END IF

	END IF

	IF ((GEP(1,NN+1).EQ.0).AND.(GEP(2,NN+1).EQ.1)) THEN

 	IF (OPT1/SUM.LT.0.0065)	THEN
	FLAGGE=FLAGGE+1
	GOTO 51
	END IF

	IF ((TAGET_B(NN)+TAGET_B(NN-1)).GT.-5) THEN
	PUR=PUR+1.
	ELSE
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).EQ.-5) THEN
	PUR=PUR+0.5
	END IF
	END IF
	DO I=1,NN
	IF (GEP(2,I).EQ.-1) THEN
	DISP=MAX(MOD((I-2),2),0)*0.5
	EXIT
	END IF
	END DO
	PLR=PLR+DISP

	END IF

	IF ((GEP(2,NN+1).EQ.0).AND.(GEP(1,NN+1).EQ.1)) THEN

  	IF (OPT1/SUM.LT.0.0065)	THEN
	FLAGGE=FLAGGE+1
	GOTO 51
	END IF

	IF ((TAGET_B(1)+TAGET_B(2)).LT.-5) THEN
	PLR=PLR-0.5
	ELSE
	IF ((TAGET_B(1)+TAGET_B(2)).EQ.-5) THEN
	PLR=PLR-1.
	ELSE
	PLR=PLR-1.5
	END IF
	END IF
	DO I=1,NN
	IF (GEP(1,I).EQ.1) THEN
	DISP=MAX(MOD((NN-1-I),2),0)*0.5
	EXIT
	END IF
	END DO
	PUR=PUR-DISP

	END IF

	IF ((GEP(1,NN+1).GT.1).AND.(GEP(2,NN+1).GT.1)) THEN
	KINK1=0
	KINK2=0
	FLAG=0

	DO I=1,NN
	IF ((GEP(1,I)*GEP(4,I).LT.0).OR.(GEP(1,I).EQ.GEP(2,I))) THEN
	IF (FLAG.EQ.0) THEN
	KINK1=I
	FLAG=1
	CYCLE
	ELSE
	IF (FLAG.EQ.1) THEN
	FLAG=2
	CYCLE
	END IF
	END IF
	IF (FLAG.EQ.2) THEN
	KINK2=I
	END IF
	END IF
	END DO

	IF (KINK2.EQ.0) THEN 

	IF (KINK1.LT.NN/2) THEN
	DISP=MAX(MOD((KINK1+1),2),0)*0.5
	PLR=PLR+DISP
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).GT.-5) THEN
	PUR=PUR+1.
	ELSE
	IF ((TAGET_B(NN)+TAGET_B(NN-1)).EQ.-5) THEN
	PUR=PUR+0.5
	END IF
	END IF

	ELSE
	DISP=MAX(MOD((NN+2-KINK1),2),0)*0.5
	PUR=PUR-DISP
	IF ((TAGET_B(1)+TAGET_B(2)).LT.-5) THEN
	PLR=PLR-0.5
	ELSE
	IF ((TAGET_B(1)+TAGET_B(2)).EQ.-5) THEN
	PLR=PLR-1.
	ELSE
	PLR=PLR-1.5
	END IF
	END IF

	END IF
	
	IF (KINK2.NE.0)	THEN
	DISP=MAX(MOD((KINK1+1),2),0)*0.5
	PLR=PLR+DISP
 	DISP=MAX(MOD((NN+2-KINK2),2),0)*0.5
	PUR=PUR-DISP
	END IF

    END IF

	END IF

	IF (PUR.LT.PURMI) THEN
	PUR=PURMI
	END IF
	IF (PUR.GT.PURMA) THEN
	PUR=PURMA
	END IF
	IF (PLR.LT.PLRMI) THEN
	PLR=PLRMI
	END IF
	IF (PLR.GT.PLRMA) THEN
	PLR=PLRMA
	END IF



	END IF

	WRITE(23,*) 'RUN GA AND TRANSFORMATION AGAIN'
	WRITE(24,*) 'RUN GA AND TRANSFORMATION AGAIN'
	WRITE(*,*) 'RUN GA AND TRANSFORMATION AGAIN'
	tMAX=FLOOR(LOG10(tbr))+PUR 
	tMIN=FLOOR(MIN(LOG10(tbr),LOG10(trep*ALPHA/3/LBAR/TL)))+PLR

51	FLAGGE=FLAGGE+1


	END DO

37	WRITE(24,*) 'RELAXATION TIME CALCULATION FINISH'
	WRITE(*,*) 'RELAXATION TIME CALCULATION FINISH'


!==================================================================
!	        GREATING TRANSFORMED G'&G" FOR LOW FREQUENCY 
!==================================================================


	DO KK=1,NUMOU		  ! GENERATE SIMULATED G'&G" FOR LOW FREQUENCY
	W=10**(FMI+DW*KK)
	GGF(KK)=0.
	GGGF(KK)=0.
	DO I=1,NN
	GGF(KK)=GGF(KK)+TAGET_A(I)*10.**(TAGET_B(I))*(W*TAGET_TAO(I))**2./(1.+(W*TAGET_TAO(I))**2.)
	GGGF(KK)=GGGF(KK)+TAGET_A(I)*10.**(TAGET_B(I))*(W*TAGET_TAO(I))/(1.+(W*TAGET_TAO(I))**2.)
	END DO
	END DO

	DO J=1,NUMIN		  ! GENERATE SIMULATED G'&G" FOR FITTING ERROR CALCULATION 
	W=FQ(J)
	GGE(J)=0.
	GGGE(J)=0.
	DO I=1,NN
	GGE(J)=GGE(J)+TAGET_A(I)*10.**(TAGET_B(I))*(W*TAGET_TAO(I))**2/(1+(W*TAGET_TAO(I))**2)
	GGGE(J)=GGGE(J)+TAGET_A(I)*10.**(TAGET_B(I))*(W*TAGET_TAO(I))/(1+(W*TAGET_TAO(I))**2)
	END DO
	END DO

	IF (OUTGW.EQ.1)	THEN
	OPEN(12,FILE='G_w.DAT')	   ! WRITE OUTPUT FILE FOR NORMALIZED LOW FREQUENCY G'&G"
    WRITE(12,*) 'ITERATION',JJ   
	WRITE(12,*) 'PARAMETERS PART'
	WRITE(12,*) 'RATIO',RATIO
	WRITE(12,*) 'TIME INTERVAL',DT	
	WRITE(12,*) 'MICELLE LENGTH',LBAR*TL 	
    WRITE(12,*) 'PLATAEU',G0
	WRITE(12,*) 'Le',Le 
    WRITE(12,*) 'Lp',Lp    
	WRITE(12,*) 'DATA PART'
    DO I=1,NUMOU
	WRITE(12,*) 10**(FMI+DW*I),GGF(I),GGGF(I)
    END DO
	CLOSE(12)
	END IF

    DO KK=1,NUMG			  ! FITTED G(t) GENERATE BY GA
	GF(KK)=0.
	DO I=1,NN
	GF(KK)=GF(KK)+TAGET_A(I)*10.**(TAGET_B(I))*EXP(-1.*T(KK)/TAGET_TAO(I))
	END DO
	END DO


	F_ERR=0.				  ! CALCULATE TRANSFORAMTION ERROR
	DO K=1,NUMG
	GF(K)=0.
	DO I=1,NN
	IF (T(K)/TAGET_TAO(I).GT.500.) THEN
	GF(K)=GF(K)+0.
	ELSE
	IF (T(K)/TAGET_TAO(I).LT.0.001)	THEN
 	GF(K)=GF(K)+TAGET_A(I)*10.**(TAGET_B(I))
	ELSE
	GF(K)=GF(K)+TAGET_A(I)*10.**(TAGET_B(I))*EXP(-1.*T(K)/TAGET_TAO(I))
	END IF
	END IF
	END DO
	F_ERR=F_ERR+ABS(G(K)-GF(K))
	END DO

	IF (OUTGFT.EQ.1) THEN
 	OPEN(7,FILE='GF_t.DAT')	  ! WRITE OUTPUT FILE FOR FITTED G(t) GENERATE BY GA 
 	WRITE(7,*) 'PARAMETERS PART'
 	WRITE(7,*) 'RATIO',RATIO
 	WRITE(7,*) 'TIME INTERVAL',DT	
 	WRITE(7,*) 'MICELLE LENGTH',LBAR*TL 	
    WRITE(7,*) 'PLATAEU',G0
 	WRITE(7,*) 'Le',Le 
    WRITE(7,*) 'Lp',Lp    
 	WRITE(7,*) 'DATA PART'
    DO I=1,NUMG
	WRITE(7,*) T(I),GF(I)
    END DO
	CLOSE(7)
	END IF

	OPEN(8,FILE='G&TAO.DAT')  ! WRITE OUTPUT FILE FOR MIU_I AND TAO_I GENERATE BY GA
    WRITE(8,*) 'ITERATION',JJ
	WRITE(8,*) 'PARAMETERS PART'
	WRITE(8,*) 'RATIO',RATIO
	WRITE(8,*) 'TIME INTERVAL',DT	
	WRITE(8,*) 'MICELLE LENGTH',LBAR*TL 	
    WRITE(8,*) 'PLATEAE',G0
	WRITE(8,*) 'Le',Le 
    WRITE(8,*) 'Lp',Lp    
	WRITE(8,*) 'DATA PART'
    WRITE(8,*)	'TOTAl ERROR',F_ERR/SUM
    DO I=1,NN
	WRITE(8,*) TAGET_A(I)*10**TAGET_B(I),TAGET_TAO(I)
    END DO
	CLOSE(8)


!==================================================================
!				    HIGH FREQUENCY SIMULATION
!==================================================================


	IF (LROUSE.EQ.1) THEN  ! ROUSE MODES
	DO I=1,NUMOU
	W=10**(FMI+DW*I)
	GGL=0.
    GGGL=0.
	DO J=1,M
	Z=CEILING((1+(J-1)*N)/(Le/Lp)*TL)
	NM=CEILING(ALPHA/2.*Z)
	IF (Z.GE.1) THEN
	te=trep/3./Z**3*((1+(J-1)*N)/LBAR)**3
	ELSE
	CYCLE 
	END IF
	GGR=0.
	GGGR=0.
	DO K=Z,NM
	GGR=GGR+1./(4.*(K/Z)**4+(W*te)**2)
	GGGR=GGGR+2.*(K/Z)**2/(4.*(K/Z)**4+(W*te)**2)
	END DO
	GGR=GGR*5./4.*(W*te)**2*DLENGTH(J,1)/NUM/Z*PHI
	GGGR=GGGR*5./4.*W*te*DLENGTH(J,1)/NUM/Z*PHI
	GGL=GGL+GGR
	GGGL=GGGL+GGGR
	END DO
	GGF(I)=GGF(I)+GGL
	GGGF(I)=GGGF(I)+GGGL
	END DO

	DO I=1,NUMIN
	W=FQ(I)
	GGL=0.
    GGGL=0.
	DO J=1,M
	Z=CEILING((1+(J-1)*N)/(Le/Lp)*TL)
	NM=CEILING(ALPHA/2.*Z)
	IF (Z.GE.1) THEN
	te=trep/3./Z**3*((1+(J-1)*N)/LBAR)**3
	ELSE
	CYCLE 
	END IF
	GGR=0.
	GGGR=0.
	DO K=Z,NM
	GGR=GGR+1./(4.*(K/Z)**4+(W*te)**2)
	GGGR=GGGR+2.*(K/Z)**2/(4.*(K/Z)**4+(W*te)**2)
	END DO
	GGR=GGR*5./4.*(W*te)**2*DLENGTH(J,1)/NUM/Z*PHI
	GGGR=GGGR*5./4.*W*te*DLENGTH(J,1)/NUM/Z*PHI
	GGL=GGL+GGR
	GGGL=GGGL+GGGR
	END DO
	GGE(I)=GGE(I)+GGL
	GGGE(I)=GGGE(I)+GGGL
	END DO
	WRITE(24,*) 'ROUSE MODEL CORRECTION FINISH'
	WRITE(*,*) 'ROUSE MODEL CORRECTION FINISH'

	IF (OUTR.EQ.1) THEN
	OPEN(9,FILE='ROUSE.DAT')  ! WRITE OUTPUT FILE FOR NORMALIZED G'&G" WITH HIGH FREQUENCY ROUSE MODES
	WRITE(9,*) 'PARAMETERS PART'
	WRITE(9,*) 'RATIO',RATIO
	WRITE(9,*) 'TIME INTERVAL',DT	
	WRITE(9,*) 'MICELLE LENGTH',LBAR*TL 	
    WRITE(9,*)  'PLATAEU',G0 
    WRITE(9,*)  'Le',Le 
    WRITE(9,*)  'Lp',Lp 
 	WRITE(9,*)	'DATA PART'
    DO I=1,NUMOU
 	WRITE(9,*) 10**(FMI+DW*I),GGF(I),GGGF(I)
    END DO
 	CLOSE(9)
	END IF
    END IF

	IF (LBEND.EQ.1) THEN	! BENDING MODES
	DO I=1,NUMOU
	W=10**(FMI+DW*I)
	GGF(I)=GGF(I)*G0
    GGGF(I)=GGGF(I)*G0
	GGF(I)=GGF(I)+ST*W**0.75
	GGGF(I)=GGGF(I)+OS*W**0.75+W*Vs
	END DO

	DO I=1,NUMIN
	W=FQ(I)
	GGE(I)=GGE(I)*G0
    GGGE(I)=GGGE(I)*G0
	GGE(I)=GGE(I)+ST*W**0.75
	GGGE(I)=GGGE(I)+OS*W**0.75+W*Vs
	END DO
	WRITE(24,*) 'BENDING CORRECTION FINISH'
	WRITE(*,*) 'BENDING CORRECTION FINISH'

    END IF

	WRITE(24,*) JJ,'LOOP FINISH'
	WRITE(24,*) 'SIGN',REM
	WRITE(*,*) JJ,'LOOP FINISH'
	WRITE(*,*) 'SIGN',REM


!==================================================================
!			 FINDING SIUMLATED LOCAL RHEOLOGICAL FEATURE
!==================================================================


	FQFMA=10**(FMI+DW)	       ! SIMULATED MAXIMUM G" FREQUECNY
	GGFMA=GGF(1)			   ! SIMULATED VALUE OF G' FOR MAXIMUM G"
	GGGFMA=GGGF(1)			   ! SIMULATED VALUE OF MAXIMUM G"  
	FQFMI=10**(FMI+DW*NUMOU)   ! SIMULATED MINIMUM G" FREQUECNY
	GGFMI=GGF(NUMOU)		   ! SIMULATED VALUE OF G' FOR MINIMUM G"
	GGGFMI=GGGF(NUMOU)		   ! SIMULATED VALUE OF MINIMUM G" 
	FLAGW=0					   ! FLAG FOR NO APPEARANT MAXIMUM AND MINIMUM G" IN SIMULATED DATA

	DO J=2,NUMOU-1			   
	IF ((GGGF(J).GE.GGGF(J+1)).AND.(GGGF(J).GE.GGGF(J-1))) THEN
	IF (GGGF(J).GE.GGGFMA) THEN
	FQFMA=10**(FMI+DW*J)
	GGFMA=GGF(J)
	GGGFMA=GGGF(J)
	FLAGW=1
	END IF
	END IF
	IF ((GGGF(J).LE.GGGF(J+1)).AND.(GGGF(J).LE.GGGF(J-1))) THEN
	IF (GGGF(J).LE.GGGFMI) THEN
	FQFMI=10**(FMI+DW*J)
	GGFMI=GGF(J)
	GGGFMI=GGGF(J)
	END IF
	END IF
	IF (FLAGMM.EQ.1) THEN
	IF ((GGF(J).GE.GGGF(J)).AND.(GGF(J+1).LE.GGGF(J+1))) THEN
	FQFC=10**(FMI+DW*J)
	END IF
	END IF
	IF (FLAGMR.EQ.0) THEN
	IF ((GGGF(J+1).GE.GGF(J+1)).AND.(GGGF(J-1).LE.GGF(J-1))) THEN
	FQFSC=10**(FMI+DW*J)
	END IF
	END IF
	END DO

	IF (FLAGW.EQ.0)	THEN

	DO J=1,NUMOU-1
	IF ((GGGF(J+1).LE.GGF(J+1)).AND.(GGGF(J-1).GE.GGF(J-1))) THEN
	FQFC=10**(FMI+DW*J)
	EXIT
	END IF
	END DO
	FQFMA=FQMA/FQC*FQFC
	FQFMI=FQMI/FQC*FQFC
	FLAG=0

 	DO J=1,NUMOU-1
	XCH=10**(FMI+DW*J)
	IF (FLAG.EQ.0) THEN
	IF ((XCH*10**DW.GE.FQFMA).AND.(XCH/10**DW.LE.FQFMA)) THEN
	GGFMA=GGF(J)
	GGGFMA=GGGF(J)
	FLAG=1
	END IF
	ELSE
  	IF ((XCH*10**DW.GE.FQFMI).AND.(XCH/10**DW.LE.FQFMI)) THEN
	GGFMI=GGF(J)
	GGGFMI=GGGF(J)
	EXIT
	END IF
	END IF
	END DO

	FLAGW=1
	END IF


!==================================================================
!			CALCULATING FITTING ERRORS AND DIFFERENCE
!==================================================================
				

	SERR1=0					! THE NUMBER OF REGIONS WHOSE FITTING ERROR IS LESS THAN 0.1
	SERR2=0					! THE NUMBER OF SATISIFIED DIFFERNECE
	FERRMA=0.
	PERRMA=0.

	FERR1=0.				! THE AVERAGE FITTING ERROR FOR FIRST REGION
	DO I=1,IDMA
	FERR1=FERR1+(LOG(GGE(I)/GG(I))+LOG(GGGE(I)/GGG(I)))/2./IDMA
	END DO
	IF (ABS(FERR1).LT.0.1) THEN
	SERR1=SERR1+1
	ELSE
	FERRMA=FERRMA+ABS(FERR1)
	END IF
	WRITE(20,*) 'FERROR1:',FERR1
	WRITE(*,*) 'FERROR1:',FERR1

	FERR2=0.			    ! THE AVERAGE FITTING ERROR FOR SECOND REGION
	DO I=IDMA+1,IDMI
	FERR2=FERR2+(LOG(GGGE(I)/GGG(I))+LOG(GGE(I)/GG(I)))/2./(IDMI-IDMA)
	END DO
	IF (ABS(FERR2).LT.0.1) THEN
	SERR1=SERR1+1
	ELSE
	FERRMA=FERRMA+ABS(FERR2)
	END IF
	WRITE(20,*) 'FERROR2:',FERR2
	WRITE(*,*) 'FERROR2:',FERR2

	FERR3=0.			    ! THE AVERAGE FITTING ERROR FOR THIRD REGION
	DO I=IDMI+1,IDH
	FERR3=FERR3+(LOG(GGGE(I)/GGG(I))+LOG(GGE(I)/GG(I)))/2./(IDH-IDMI)
	END DO
	IF (FLAGMR.EQ.1) THEN
	IF (ABS(FERR3).LT.0.1) THEN
	SERR1=SERR1+1
	ELSE
	FERRMA=FERRMA+ABS(FERR3)
	END IF
    END IF
	WRITE(20,*) 'FERROR3:',FERR3
	WRITE(*,*) 'FERROR3:',FERR3

	FERR4=0.				! THE AVERAGE FITTING ERROR FOR FORTH REGION
	DO I=IDH+1,NUMIN
	FERR4=FERR4+(LOG(GGGE(I)/GGG(I))+LOG(GGE(I)/GG(I)))/2./(NUMIN-IDH)
	END DO
!	IF (ABS(FERR4).LT.0.1) THEN
!	SERR1=SERR1+1
!	ELSE
!	FERRMA=FERRMA+ABS(FERR4)
!	END IF
	WRITE(20,*) 'FERROR4:',FERR4
	WRITE(*,*) 'FERROR4:',FERR4

	PERR1=ECPC1*ABS(LOG(GGMA/GGFMA))+ECPC2*ABS(LOG(GGGMA/GGGFMA))  ! MAGITUDE DIFFERNECE OF MAXIMUM G" POINT BETWEEN EXPERIMENT AND SIMULATION  
	IF (PERR1.LT.0.1)	THEN
	SERR2=SERR2+1
	ELSE
	PERRMA=PERRMA+ABS(PERR1)
	END IF
	WRITE(20,*) 'PERROR1:',PERR1
	WRITE(*,*) 'PERROR1:',PERR1

	PERR2=LOG(FQMA/FQFMA)	! FREQUENCY DIFFERNECE OF MAXIMUM G" POINT BETWEEN EXPERIMENT AND SIMULATION
	IF (ABS(PERR2).LT.0.1)	THEN
	SERR2=SERR2+1
	ELSE
	PERRMA=PERRMA+ABS(PERR2)
	END IF
	WRITE(20,*) 'PERROR2:',PERR2
	WRITE(*,*) 'PERROR2:',PERR2

	PERR3=LOG(GGGMI/GGGFMI)	! MAGITUDE DIFFERNECE OF MINIMUM G" POINT BETWEEN EXPERIMENT AND SIMULATION
	IF (ABS(PERR3).LT.0.1)	THEN
	SERR2=SERR2+1
	ELSE
	PERRMA=PERRMA+ABS(PERR3)
	END IF
	WRITE(20,*) 'PERROR3:',PERR3
	WRITE(*,*) 'PERROR3:',PERR3

	PERR4=LOG(FQMI/FQFMI)	! FREQUENCY DIFFERNECE OF MINIMUM G" POINT BETWEEN EXPERIMENT AND SIMULATION
	IF (ABS(PERR4).LT.0.1)	THEN
	SERR2=SERR2+1
	ELSE
	PERRMA=PERRMA+ABS(PERR4)
	END IF
	WRITE(20,*) 'PERROR4:',PERR4
	WRITE(*,*) 'PERROR4:',PERR4

 	IF (FLAGMR.EQ.0) THEN
	PERR5=LOG(FQSC/FQFSC)	! FREQUENCY DIFFERNECE OF SECOND CROSSOVER POINT BETWEEN EXPERIMENT AND SIMULATION
	IF (ABS(PERR5).LT.0.1)	THEN
	SERR1=SERR1+1
	ELSE
	FERRMA=FERRMA+ABS(PERR5)
	END IF
	WRITE(20,*) 'PERROR5:',PERR5
	WRITE(*,*) 'PERROR5:',PERR5
	END IF

	IF (FLAGMR.EQ.0) THEN
 	FERR=ABS(FERR1)+ABS(FERR2)+ABS(PERR5)
	ELSE
	FERR=ABS(FERR1)+ABS(FERR2)+ABS(FERR3)
	END IF
	PERR=ABS(PERR1)+ABS(PERR2)+ABS(PERR3)+ABS(PERR4)
	FERR5=(ABS(FERR3)+ABS(FERR4))/2.	! ERROR USED FOR ITERATING lp

	IF (SERR1.EQ.3)	THEN
	FERRMA=0.
	ELSE
	FERRMA=FERRMA/(3-SERR1)
	END IF
	IF (SERR2.EQ.4)	THEN
	PERRMA=0.
	ELSE
	PERRMA=PERRMA/(4-SERR2)
	END IF

	IF (FLAGH.EQ.0)	THEN
	FERR5=FERR3
	END IF
	IF (FLAGMM.EQ.1) THEN
	FERR5=FERR4
	END IF

	IF (FLAGMR.EQ.1) THEN
	IF ((ABS(FERR1).LT.0.1).AND.(ABS(FERR2).LT.0.1).AND.(ABS(FERR5).LT.0.1).AND.(ABS(FERR4).LT.0.1)) THEN
	IF ((PERR1.LT.0.05).AND.(ABS(PERR2).LT.0.1).AND.(ABS(PERR3).LT.0.05).AND.(ABS(PERR4).LT.0.1)) THEN
	FLAGJJ=1
	END IF
	END IF
	ELSE
	IF ((ABS(FERR1).LT.0.1).AND.(ABS(FERR2).LT.0.1).AND.(ABS(FERR3).LT.0.1).AND.(ABS(PERR5).LT.0.1)) THEN
	IF ((PERR1.LT.0.05).AND.(ABS(PERR2).LT.0.1).AND.(ABS(PERR3).LT.0.05).AND.(ABS(PERR4).LT.0.1)) THEN
	FLAGJJ=1
	END IF
	END IF
	END IF

	IF (JJ.GT.2) THEN
	IF (SERR1.GT.SERRM1) THEN
	FLAGPR=1				! FLAG FOR WRITING/OVER-WRITING OUTPUT FILE FOR SIMULATED G'&G" WITH MINIMUM FITTING ERROR AND DIFFENERCE  
	END IF
	IF (SERR1.EQ.SERRM1) THEN

	IF (SERR2.GT.SERRM2) THEN
	FLAGPR=1				 
	ELSE
	IF (SERR2.EQ.SERRM2) THEN
	IF (FERRMA.LT.FERRM) THEN
	FLAGPR=1
	END IF
	IF ((FERRMA.EQ.FERRM).AND.(PERRMA.LT.PERRM)) THEN
	FLAGPR=1
	END IF
	END IF
	END IF

	END IF
	END IF

!	G0=103.5
!   RATIO=3.276
!	ALPHA=1.465
!	La=2.54*10.**(-6.)
				   
	IF (FLAGPR.EQ.1) THEN
	LpF=Lp
	dF=d
	ALPHAF=ALPHA
	G0F=G0
	RATIOF=RATIO
	trepF=trep
	ZfF=Zf
	JJF=JJ

	SERRM1=SERR1
	SERRM2=SERR2
	FERRM=FERRMA
	PERRM=PERRMA

	OPEN(10,FILE='RESULT_v1.6.2.DAT')	! WRITE/OVER-WRITE OUTPUT FILE FOR SIMULATED G'&G" WITH MINIMUM FITTING ERROR AND DIFFENERCE
    WRITE(10,*) 'ITERATION:',JJ
	WRITE(10,*) 'PARAMETERS PART'
	WRITE(10,*) 'RATIO',RATIO
	WRITE(10,*) 'TIME INTERVAL',DT
	WRITE(10,*)	'REPTATION TIME',trep
 	WRITE(10,*)	'BREAKAGE TIME',trep*RATIO
	WRITE(10,*) 'MICELLE LENGTH',LBAR*TL*Lp
	WRITE(10,*) 'PLATAEU',G0	
    WRITE(10,*) 'Le',Le 
    WRITE(10,*) 'Lp',Lp  
    WRITE(10,*) 'd',d 	  
	WRITE(10,*) 'DATA PART'
    DO I=1,NUMOU
	WRITE(10,*) 10**(FMI+DW*I),GGF(I),GGGF(I)
    END DO
	CLOSE(10)
	END IF

	IF ((ABS(FERR1).LT.0.1).AND.(ABS(LOG(RATIOU/RATIOL)).LE.0.10).AND.(ABS(LOG(trepU/trepL)).LE.0.10)) THEN
	FLAGG=1
	END IF

	IF (FLAGJJ.EQ.1) THEN
	WRITE(*,*) JJ,' ITERATION SUCCEED'
	WRITE(24,*) JJ,' ITERATION SUCCEED'
	GOTO 40
	END IF


!==================================================================
!		    	OPTIMIZATION OF MICELLE PARAMETERS
!==================================================================


	IF (JJ.LE.2) THEN
	PLp=0.5
	ELSE
	PLp=1.
	END IF


	IF (JJ.LT.NNN) THEN

 	G0ER1=(ECPC2*GGGFMA+ECPC1*GGFMA)/(ECPC1+ECPC2)
	G0ER2=(ECPC2*GGGMA+ECPC1*GGMA)/(ECPC1+ECPC2)
	RATIO1=RATIO
	trep2=trep
	G01=G0
	Zf1=Zf
	ALPHA1=ALPHA

	IF (FQFMA.GT.FQMA) THEN	  ! EVOLUTION FOR BOUNDARIES OF RATIO, lp, trep DURING EACH ITERATION 

	RATIOUU=RATIO*(FQFMA/FQMA)**1.5	
	IF (RATIOUU.GT.RATIOU) THEN
	RATIOUU=RATIOU
	END IF
	RATIOLL=RATIO*(FQFMA/FQMA)**(-1.5)
	IF (RATIOLL.LT.RATIOL) THEN
	RATIOLL=RATIOL
	END IF

	ELSE
	RATIOLL=RATIO*(FQFMA/FQMA)**1.5
	IF (RATIOLL.LT.RATIOL) THEN
	RATIOLL=RATIOL
	END IF
	RATIOUU=RATIO*(FQFMA/FQMA)**(-1.5)
	IF (RATIOUU.GT.RATIOU) THEN
	RATIOUU=RATIOU
	END IF

	END IF

	IF (FERR1.LT.0) THEN

	trepUU=trep/EXP(FERR1/1.5)
	IF (trepUU.GT.trepU) THEN
	trepUU=trepU
	END IF
	trepLL=trep*EXP(FERR1/1.5)
	IF (trepLL.LT.trepL) THEN
	trepLL=trepL
	END IF

	ELSE
	trepLL=trep/EXP(FERR1/1.5)
	IF (trepLL.LT.trepL) THEN
	trepLL=trepL
	END IF
	trepUU=trep*EXP(FERR1/1.5)
	IF (trepUU.GT.trepU) THEN
	trepUU=trepU
	END IF

	END IF


	IF (FLAGMR.EQ.1)  THEN

	IF (FQFMI.GT.FQMI) THEN
	LpUU=Lp*(FQFMI/FQMI)**(1./3.*PLp)
	IF (LpUU.GT.LpU) THEN
	LpUU=LpU
	END IF
	LpLL=Lp*(FQFMI/FQMI)**(-1./3.*PLp)
	IF (LpLL.LT.LpL) THEN
	LpLL=LpL
	END IF

	ELSE
	IF (FQFMI.LT.FQMI) THEN
	LpLL=Lp*(FQFMI/FQMI)**(1./3.*PLp)
	IF (LpLL.LT.LpL) THEN
	LpLL=LpL
	END IF
	LpUU=Lp*(FQFMI/FQMI)**(-1./3.*PLp)
	IF (LpUU.GT.LpU) THEN
	LpUU=LpU
	END IF
	END IF
	END IF

	ELSE

	IF (FQFSC.GT.FQSC) THEN
	LpUU=Lp*(FQFSC/FQSC)**(PLp/3.)
	IF (LpUU.GT.LpU) THEN
	LpUU=LpU
	END IF
	LpLL=Lp*(FQSC/FQFSC)**(PLp/3.)
	IF (LpLL.LT.LpL) THEN
	LpLL=LpL
	END IF

	ELSE
	IF (FQFSC.LT.FQSC) THEN
	LpLL=Lp*(FQFSC/FQSC)**(PLp/3.)
	IF (LpLL.LT.LpL) THEN
	LpLL=LpL
	END IF
	LpUU=Lp*(FQSC/FQFSC)**(PLp/3.)
	IF (LpUU.GT.LpU) THEN
	LpUU=LpU
	END IF
	END IF
	END IF

	END IF


!	IF (FLAGMM.EQ.1) THEN
!	IF (FQC.GT.FQFC) THEN
!	LpUU=Lp*FQC/FQFC
!	LpLL=Lp*FQFC/FQC
!	ELSE
!	LpUU=Lp*FQFC/FQC
!	LpLL=Lp*FQC/FQFC
!	END IF
!   LpUU=LpU
!	LpLL=LpL
!	END IF


	IF (MOD((JJ-1),2).EQ.0) THEN	! EVOLUTION FOR MICELLE PARAMETERS DURING EACH ITERATION


	IF (SLP.EQ.0) THEN

	IF (FLAGMR.EQ.0) THEN
	IF (ABS(LOG(FQSC/FQFSC)).GT.0.05) THEN
	Lp=Lp*(FQFSC/FQSC)**(PLp/3.)
	END IF

	ELSE
	IF (FLAGMM.EQ.1) THEN
	IF ((ABS(LOG(FQC/FQFC)).GT.0.05).AND.(ABS(FERR5).GT.0.05)) THEN
	Lp=Lp*((FQFC/FQC)+3.*EXP(-0.8*FERR5*PLp))/4.
	END IF
	ELSE
	Lp=Lp*(FQFMI/FQMI)**(PLp/3.)
	END IF
	END IF

	IF (Lp.GT.LpUU) THEN
	Lp=LpUU
	END IF
	IF (Lp.LT.LpLL) THEN
	Lp=LpLL
	END IF

	END IF
						
	DO I=1,40
	IF (ABS(LOG(FQFMA/FQMA)).GT.0.05) THEN
	trep1=trep*FQFMA/FQMA*(RATIO/RATIO1)**(2./3.*PCOR)*(ALPHA1/ALPHA)**3.
	ELSE
	trep1=trep
	END IF
	IF (trep1.GT.trepUU) THEN
	trep1=trepUU
	END IF
	IF (trep1.LT.trepLL) THEN
	trep1=trepLL
	END IF

	IF (I.EQ.40) THEN
	trep=trep2
	G0=G01
	Zf=Zf1
	RATIO=RATIO1
	ALPHA=ALPHA1
	EXIT
	END IF


	IF (ABS(LOG(G0ER1/G0ER2)).GT.0.01) THEN
	
	IF (GGGMA/G0.LT.0.47) THEN
	G01=G0ER2/(G0ER1/G0-0.0624*LOG10(RATIO1/RATIO))
	ELSE
	G01=G0ER2*G0/G0ER1*(RATIO1/RATIO)**0.24
	END IF
	IF (G01.GE.G0MA) THEN
	G01=G0MA
	END IF
	IF (G01.LE.G0MI)	THEN
	G01=G0MI
	END IF

	ELSE
	G01=G0
	END IF

	C1=9.75*Kb*TEM/Lp**3./G01
	C2=3.*28./5./PI*Kb*TEM*PHI/d**2./G01/Lp
!	C1=9.75*Kb*TEM/Lp**3./ALPHA1**1.8
!	C2=28./5./PI*Kb*TEM*PHI/d**2./ALPHA1/Lp
!	G01=(C1*ALPHA1**3.+C2*3.)/(3.+ALPHA1**3.)

	DO J=1,50
	IF ((C1*ALPHA1**2.2+C2-3.*ALPHA1).LT.(APHMI**4.)) THEN
	ALPHA1=APHMI
	ELSE
	ALPHA1=(C1*ALPHA1**2.2+C2-3.*ALPHA1)**0.25
	END IF
	END DO
	IF (ALPHA1.GE.APHMA) THEN
	ALPHA1=APHMA
	END IF
	IF (ALPHA1.LE.APHMI) THEN
	ALPHA1=APHMI
	END IF


    TL=SQRT(ALPHA1/2.)	         
	IF (ALPHA1.LT.2) THEN
	TL=1.
	END IF      
	Le=ALPHA1*Lp    	             
	ZETA=Le**0.6*Lp**0.4        
	FIC=2.*PI*Vs/LOG(ZETA/d)	  
	D0=Kb*TEM/FIC
	ZfU=(MIN(trepUU,trepMA)/TL*D0*PI**2.)**(1./3.)/Lp/ALPHA1*TL*1.
	ZfL=(MAX(trepLL,trepMI)/TL*D0*PI**2.)**(1./3.)/Lp/ALPHA1*TL/1.

	IF (ABS(LOG(GGGFMI/GGGMI)).GT.0.02) THEN
 	DO K=1,20
	IF (ALPHA1.GT.1.5) THEN
	IF (Zf1.LT.((1.33/RATIO1)**0.8)) THEN
	Zf1=Zf*(GGGFMI*G01/GGGMI/G0)
	ELSE
	Zf1=Zf*(GGGFMI*G01/GGGMI/G0)**(4./3.)
	END IF
	ELSE
	Zf1=Zf*(GGGFMI*G01/GGGMI/G0)**(4./3.)*(ALPHA1/ALPHA)**0.55
	END IF
	END DO
	ELSE
	Zf1=Zf
	END IF

	IF (Zf1.GT.1.2*ZfU) THEN
	Zf1=1.2*ZfU
	END IF
	IF (Zf1.LT.0.8*ZfL) THEN
	Zf1=ZfL*0.8
	END IF

    La=Zf1*Lp*ALPHA1/TL	
!   Zf1=La/Lp/ALPHA1								 
!   trep2=(La/TL)**3./D0/PI**2.*TL
    trep2=La**3./D0/PI**2.*TL	 

	RATIO1=RATIO*(trep*FQFMA/FQMA/trep2*(ALPHA1/ALPHA)**3.)**(1.5/PCOR)

	IF (RATIO1.GT.RATIOUU) THEN
	RATIO1=RATIOUU
	END IF
	IF (RATIO1.LT.RATIOLL) THEN
	RATIO1=RATIOLL
	END IF


	END DO

	ELSE

	IF (SLP.EQ.0) THEN
	
	IF (FLAGMR.EQ.0) THEN
	IF (ABS(LOG(FQSC/FQFSC)).GT.0.05) THEN
	Lp=Lp*(FQFSC/FQSC)**(PLp/3.)
	END IF

	ELSE
	IF (FLAGMM.EQ.1) THEN
	IF ((ABS(LOG(FQC/FQFC)).GT.0.05).AND.(ABS(FERR5).GT.0.05)) THEN
	Lp=Lp*((FQFC/FQC)+3.*EXP(-0.8*FERR5*PLp))/4.
	END IF
	ELSE
	IF (ABS(LOG(FQMI/FQFMI)).GT.0.05) THEN
	Lp=Lp*(FQFMI/FQMI)**(1./3.*PLp)
	END IF
	END IF
	END IF

	IF (Lp.GT.LpUU) THEN
	Lp=LpUU
	END IF
	IF (Lp.LT.LpLL) THEN
	Lp=LpLL
	END IF

	END IF

    IF (SD.EQ.0) THEN

	d1=d
	d2=d
	dER1=FERR3-1.25*LOG(Lp/Lp0)
	IF (FLAGH.EQ.1)	THEN
	dER2=FERR4-1.25*LOG(Lp/Lp0)
	ELSE
	dER2=0.
	END IF
	IF (ABS(dER1).GT.0.025) THEN
    d1=d*EXP(0.5*dER1)
	END IF 
	IF (ABS(dER2).GT.0.025) THEN
	d2=d*EXP(0.5*dER2)
	END IF
	
	IF (ABS(FERR4).GT.0.05)	THEN
	d2=d*EXP(0.5*dER2)
	END IF 

	d=(d1**ECPC1*d2**ECPC2)**(1./(ECPC1+ECPC2))
	IF (d.GT.dMA) THEN
	d=dMA
	END IF
	IF (d.LT.dMI) THEN
	d=dMI
	END IF

	END IF

	DO J=1,40
	IF (ABS(FERR1).GT.0.05) THEN
	RATIO=RATIO1*(trep2/trep/EXP(FERR1/1.5)*(ALPHA/ALPHA1)**3.)**(1.5/PCOR)
	END IF
	IF (RATIO.GT.RATIOUU) THEN
	RATIO=RATIOUU
	END IF
	IF (RATIO.LT.RATIOLL) THEN
	RATIO=RATIOLL
	END IF

	IF (ABS(LOG(G0ER1/G0ER2)).GT.0.01) THEN

	IF (GGGMA/G0.LT.0.47) THEN
	G0=G0ER2/(G0ER1/G01-0.0624*LOG10(RATIO/RATIO1))		 	
	ELSE
	G0=G0ER2*G01/G0ER1*(RATIO/RATIO1)**0.24	  
	END IF
	IF (G0.GE.G0MA) THEN
	G0=G0MA
	END IF
	IF (G0.LE.G0MI) THEN
	G0=G0MI
	END IF

	ELSE
	G0=G01
	END IF

	C1=9.75*Kb*TEM/Lp**3./G0
	C2=3.*28./5./PI*Kb*TEM*PHI/d**2./G0/Lp
!	C1=9.75*Kb*TEM/Lp**3./ALPHA**1.8
!	C2=28./5./PI*Kb*TEM*PHI/d**2./ALPHA/Lp
!	G0=(C1*ALPHA**3.+C2*3.)/(3.+ALPHA**3.)

	DO I=1,50
	IF ((C1*ALPHA**2.2+C2-3.*ALPHA).LT.(APHMI**4.)) THEN
	ALPHA=APHMI
	ELSE
	ALPHA=(C1*ALPHA**2.2+C2-3.*ALPHA)**0.25
	END IF
	END DO
	IF (ALPHA.GE.APHMA) THEN
	ALPHA=APHMA
	END IF
	IF (ALPHA.LE.APHMI)	THEN
	ALPHA=APHMI
	END IF


    TL=SQRT(ALPHA/2.)	         
	IF (ALPHA.LT.2) THEN
	TL=1.
	END IF      
	Le=ALPHA*Lp    	             
	ZETA=Le**0.6*Lp**0.4        
	FIC=2.*PI*Vs/LOG(ZETA/d)	  
	D0=Kb*TEM/FIC
	ZfU=(MIN(trepUU,trepMA)/TL*D0*PI**2.)**(1./3.)/Lp/ALPHA*TL*1.
	ZfL=(MAX(trepLL,trepMI)/TL*D0*PI**2.)**(1./3.)/Lp/ALPHA*TL/1.
			
	IF (ABS(FERR2).GT.0.05) THEN
 	DO I=1,20
	IF (ALPHA.GT.1.5) THEN
	IF (Zf.LT.((1.33/RATIO)**0.8)) THEN
	Zf=Zf1*EXP(FERR2)*(G01/G0)
	ELSE
	Zf=Zf1*EXP(4.*FERR2/3.)*(G0/G01)**(4./3.)
	END IF
	ELSE
	Zf=Zf1*EXP(4.*FERR2/3.)*(G0/G01)**(4./3.)*(ALPHA/ALPHA1)**0.55
	END IF
	END DO
	END IF


	IF (Zf.GT.1.2*ZfU) THEN
	Zf=1.2*ZfU
	END IF
	IF (Zf.LT.0.8*ZfL) THEN
	Zf=ZfL*0.8
	END IF


    La=Zf*Lp*ALPHA/TL
!   Zf=La/Lp/ALPHA
!	trep=(La/TL)**3./D0/PI**2.*TL							 
    trep=La**3./D0/PI**2.*TL


	END DO
  
	END IF


	IF (JJ.GT.2) THEN

	IF ((FERR1.GT.0).AND.(ABS(PERR1).LT.0.2)) THEN
	IF (RATIOU.GT.RATIOUU) THEN
	RATIOU=RATIOUU
	END IF
	IF (trepU.GT.trepUU) THEN
	trepU=trepUU
	END IF
	END IF
	IF ((FERR1.LT.0).AND.(ABS(PERR1).LT.0.2)) THEN
	IF (RATIOL.LT.RATIOLL) THEN
	RATIOL=RATIOLL
	END IF
	IF (trepL.LT.trepLL) THEN
	trepL=trepLL
	END IF	
	END IF

			
	END IF 

	IF ((JJ.GT.2).AND.(ABS(FERR1).LT.0.4)) THEN

	IF (FLAGMR.EQ.1) THEN

!	IF (FLAGMM.EQ.0) THEN
	IF (FQFMI.GT.FQMI) THEN
	IF (LpL.LT.LpLL) THEN
	LpL=LpLL	
	END IF
	END IF
	IF (FQFMI.LT.FQMI) THEN
	IF (LpU.GT.LpUU) THEN
	LpU=LpUU
	END IF
	END IF

!	ELSE
! 	IF (FQFC.GT.FQC) THEN
!	IF (LpL.LT.LpLL) THEN
!	LpL=LpLL	
!	END IF
!	END IF
!	IF (FQFC.LT.FQC) THEN
!	IF (LpU.GT.LpUU) THEN
!	LpU=LpUU
!	END IF
!	END IF
!	END IF

	ELSE

  	IF (FQFSC.GT.FQSC) THEN
	IF (LpL.LT.LpLL) THEN
	LpL=LpLL	
	END IF
	END IF
	IF (FQFSC.LT.FQSC)	THEN
	IF (LpU.GT.LpUU) THEN
	LpU=LpUU
	END IF
	END IF	

	END IF

	END IF

	WRITE(20,*) 'G0:',G0
	WRITE(*,*) 'G0:',G0
	WRITE(20,*) 'RATIO:',RATIO
	WRITE(*,*) 'RATIO:',RATIO
	WRITE(20,*) 'trep:',trep
	WRITE(*,*) 'trep:',trep
	WRITE(20,*) 'Zf:',Zf
	WRITE(*,*) 'Zf:',Zf
	WRITE(20,*) 'ALPHA:',ALPHA
	WRITE(*,*) 'ALPHA:',ALPHA
	WRITE(20,*) 'Lp:',Lp
	WRITE(*,*) 'Lp:',Lp
	WRITE(20,*) 'd:',d
	WRITE(*,*) 'd:',d
 	WRITE(20,*) 'BOUND OF RATIO:',RATIOU,RATIOL
	WRITE(*,*) 'BOUND OF RATIO:',RATIOU,RATIOL
 	WRITE(20,*) 'BOUND OF trep:',trepU,trepL
	WRITE(*,*) 'BOUND OF trep:',trepU,trepL
 	WRITE(20,*) 'BOUND OF Lp:',LpU,LpL
	WRITE(*,*) 'BOUND OF Lp:',LpU,LpL

	IF ((FERR1.LT.0.1).AND.(FERR2.LT.0.1).AND.(PERR1.LT.0.1).AND.(PERR2.LT.0.1)) THEN
	IF ((PERR3.LT.0.1).AND.(PERR4.LT.0.1).AND.(PERR5.LT.0.1)) THEN
	WRITE(20,*) 'THE RESULT CONVERGED HERE'
	END IF
	END IF

	END IF	 

	JJ=JJ+1
	WRITE(*,*) 'GOTO NEXT LOOP'
	WRITE(24,*) 'GOTO NEXT LOOP'

	END DO


!==================================================================
!		    	FINAL RESULT OF FITTING PARAMETERS
!==================================================================


40  IF ((FLAGJJ.EQ.1).OR.(JJ.EQ.NNN)) THEN
	WRITE(*,*) 'FINAL RESULT:'
	WRITE(*,*) 'ITERATION:',JJF
	WRITE(*,*) 'PLATAEU:',G0
	WRITE(*,*) 'RATIO:',RATIO	
	WRITE(*,*) 'MICELLE LENGTH:',LBAR*TL	
    WRITE(*,*) 'Le:',Le 
    WRITE(*,*) 'Lp:',Lp 
	WRITE(*,*) 'd:',d

	WRITE(20,*) 'FINAL RESULT:'
	WRITE(20,*) 'ITERATION:',JJF
	WRITE(20,*) 'PLATAEU:',G0
	WRITE(20,*) 'RATIO:',RATIO	
	WRITE(20,*) 'MICELLE LENGTH:',LBAR*TL	
    WRITE(20,*) 'Le:',Le 
    WRITE(20,*) 'Lp:',Lp 
	WRITE(20,*) 'd:',d	
	END IF   

    CLOSE(20)
	CLOSE(23)
	CLOSE(24)

    STOP
    END


  








